### ISSUE TITLE
MaxTo 2.0.0-beta2 is unable to create config.json after the fresh install

### ISSUE THREAD

**Issue by gorbunovav** [digitalcreations/MaxTo#274]
I've uninstalled the previous (1.x) version and installed 2.0.0-beta2.
It was crashing on any config-related action (settings change, regions apply and etc.).

There was no config.json file in "AppData\Roaming\MaxTo".
I've created an empty file with just "{}" as the content.
The app started to work normally after that and the file was populated with actual settings on the first launch.

**Comment by vegardlarsen** [comment]
Thank you for the report. Did you get anything in the log file at the same time that could indicate what the issue is? Could you paste the initial ~100 lines from the log file here so I can investigate?

**Comment by gorbunovav** [comment]
@vegardlarsen I am attaching the whole log file. It is the fresh install, so should be about the issue mostly.

[maxto.log](https://github.com/digitalcreations/MaxTo/files/2577932/maxto.log)

**Comment by vegardlarsen** [comment]
Thanks for this. Do you have another program in your system that registers the Windows+NumPad4 hotkey?

I believe the issue where it is trying to register that hotkey is causing all the subsequent errors in the log.

For my reference:

```
2018-11-13 20:13:33 [MaxTo.Core@2.0.0.331] [Fatal] Exception occured during startup
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> MaxTo.Core.Keyboard.HotkeyAlreadyRegisteredException: Hotkey combination already registered: Windows+NumPad4
   at MaxTo.Core.Keyboard.NativeHotkeyManager.RegisterHotkey(KeyboardCombination combination)
   at MaxTo.Core.Keyboard.HotkeyRegistrationService.Register()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Caliburn.Micro.SimpleContainer.ActivateInstance(Type type, Object[] args)
   at Caliburn.Micro.SimpleContainer.<>c__DisplayClass7_0.<RegisterSingleton>b__0(SimpleContainer container)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Caliburn.Micro.SimpleContainer.GetInstance(Type service, String key)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Caliburn.Micro.SimpleContainer.DetermineConstructorArgs(Type implementation)
   at Caliburn.Micro.SimpleContainer.<>c__DisplayClass7_0.<RegisterSingleton>b__0(SimpleContainer container)
   at Caliburn.Micro.ContainerExtensions.GetInstance[TService](SimpleContainer container, String key)
   at MaxTo.Core.MainForm.<OnLoad>d__20.MoveNext()
```

**Comment by vegardlarsen** [comment]
You are right. This definitely shouldn't cause a crash, but instead show an error message.

**Comment by vegardlarsen** [comment]
I have fixed this crash for beta.3.
