### ISSUE TITLE
Unable to install MaxTo 2.0.0-beta2

### ISSUE THREAD

**Issue by ChrisPaps** [digitalcreations/MaxTo#281]
Attempting to install on Win 10 Enterprise, with no internet. The installer never appears, but I was able to trace the log file with the attached contents.

[maxto.log](https://github.com/digitalcreations/MaxTo/files/2582086/maxto.log)

**Comment by vegardlarsen** [comment]
This is definitely a bug. Setting this on my todo-list for the next beta.

Relevant extract from the log file.
```
2018-11-14 18:02:34 [MaxTo.Core@2.0.0.331] [Fatal] Exception occured during startup
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'maxto.net'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.Core.Shims.CompatibilityShimsManager.<UpdateShimsAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.Core.Shims.CompatibilityShimsManager.<InitializeAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.Core.Settings.AsyncInitializer.<InitializeAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.Core.MainForm.<OnLoad>d__20.MoveNext()
```

**Comment by vegardlarsen** [comment]
I have fixed this and it will be in beta.3.
