### ISSUE TITLE
Setup fails due to DLLs being in use

### ISSUE THREAD

**Issue by Gappa** [digitalcreations/MaxTo#287]
Applies at least to Beta 2 and 3.

Updating the version does not work even if I shut down MaxTo manually. This is bacause these two DLLs can't be deleted:

- MaxTo.Hook.x64.dll
- MaxTo.Hook.x86.dll

In my case, the deletion of x86 version was prevented because of `Adobe CEF Helper.exe`, the x64 at first by `ApplicationFrameHost.exe` and finally by `GoogleDriveFS.exe` (the business version of Google Drive).

Googled a bit what is what, shut down all of them, deleted the DLLs manually and then the setup can proceed as usual. Restart will work too.

Info from the log (hopefully the right one):
```
2018-11-19 07:10:36 [MaxTo.Core@2.0.0.331] [Fatal] Unhandled exception "InvalidOperationException" at "   v System.Windows.Threading.Dispatcher.VerifyAccess()
   v System.Windows.Interop.HwndTarget.Dispose()
   v System.Windows.Interop.HwndSource.Dispose(Boolean disposing)
   v WindowsDesktop.Internal.RawWindow.Close()"
System.InvalidOperationException: Volající vlákno nemůže získat přístup k tomuto objektu, protože jej vlastní jiné vlákno.
```

The non-english message is something along the lines of "The caller thread cannot gain access to this object, because it is owned by a different thread." - which is kind of expected in regards to the DLLs being in use.

**Comment by vegardlarsen** [comment]
Thanks for writing. First of all; the exception is unrelated. It is caused by [a bug in the library we use for controlling virtual desktops](https://github.com/Grabacr07/VirtualDesktop/pull/28), and only occurs when MaxTo is shutting down.

Can you take a look at the installer log file? You'll find it in `%LocalAppData%\SquirrelTemp\SquirrelSetup.log`

The installer not supposed to update the files in place; it creates a new folder for each version and does not delete previous files until the next time it updates. So you'll mostly have 2 versions installed side-by-side at any time, and it shouldn't ever need to overwrite files in this manner.

**Comment by Gappa** [comment]
> First of all; the exception is unrelated. It is caused by a bug in the library we use for controlling virtual desktops, and only occurs when MaxTo is shutting down.

Ah, thanks for the clarification.

> The installer not supposed to update the files in place; it creates a new folder for each version and does not delete previous files until the next time it updates. So you'll mostly have 2 versions installed side-by-side at any time, and it shouldn't ever need to overwrite files in this manner.

Yup, I know about the "another folder" method. What I did when updating from beta2 to beta3 was simply to shut down the current version and try to let the setup.exe to update the app - which might not be the intended way, but many apps are ok with this approach. 

I'll try to post the log later, when I'm on that machine.

**Comment by vegardlarsen** [comment]
I'd be very interested in seeing the Squirrel log (Squirrel is the name of the installer we use), which may identify what is happening.

**Comment by Gappa** [comment]
[SquirrelSetup.log](https://github.com/digitalcreations/MaxTo/files/2598156/SquirrelSetup.log)

**Comment by Gappa** [comment]
Manually - downloaded the setup, shut down the previous version ("Exit" from the tray icon), lauched the new setup.

**Comment by vegardlarsen** [comment]
I don't know what causes this, but I will attempt to investigate.

**Comment by Gappa** [comment]
Thanks, I'll try to post more information if I obtain any (when updating in the future).

**Comment by vegardlarsen** [comment]
The log file is a bit confusing here; it appears that you tried to install beta.2 twice, and at that point it failed to replace the existing version because it couldn't do a side-by-side install. Afterwards, when you try to install beta.3; the install succeeds, because it can now perform a side-by-side install.

I don't know if we can fix this; I don't believe Squirrel has any way to hook into this "hey, I need to delete everything" event. I am postponing this; the fix won't be in beta.4.

**Comment by bojordan** [comment]
Installation of new versions fails for me, usually with the following error:

```
2019-02-25 08:09:24> IEnableLogger: Failed to remove existing directory on full install, is the app still running???: System.IO.IOException: The process cannot access the file 'C:\Users\rojordan\AppData\Local\MaxTo\app-2.0.0-beta10\MaxTo.Hook.x64.dll' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at Squirrel.Utility.<>c.<DeleteDirectory>b__19_0(String file)
   at Squirrel.Utility.<>c__DisplayClass12_1`1.<ForEachAsync>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

I believe it is usually something associated with Visual Studio 2017 and/or 2019 (which I run elevated) that has prevented it from installing.

Suspecting this is related to the above issue.

**Comment by vegardlarsen** [comment]
Can you try uninstalling MaxTo completely, rebooting (this step is important, don't skip it), and checking if installing the latest version works now?

**Comment by bojordan** [comment]
Sorry I failed to mention that the installer has always succeeded with a full reboot, even without uninstalling MaxTo.

**Comment by Gappa** [comment]
Haven't encoutered any problems with updates for quite a long time, currently running 2.0.1.

So this may be a non-issue for a long time :)

**Comment by vegardlarsen** [comment]
It is still an issue, and probably will be until we replace our installer with something else. If you run the installer twice, it will fail because it cannot delete the files that are currently in use.
