### ISSUE TITLE
Can't change launched program to different virtual desktop

### ISSUE THREAD

**Issue by FuujSama** [digitalcreations/MaxTo#437]
I set up a small test shortcut where I just opened VSCode and moved the window to a different virtual desktop. This, however, does not work. VSCode is opened and nothing else happens. The window doesn't even gain focus.

Relevent log:
```
2019-06-26 14:55:02 [Core@2.0.1.499] [Information] Executing recipe '"Tests"' with 2 ingredients
2019-06-26 14:55:02 [Core@2.0.1.499] [Warning] Received exception from command request 2 while executing '"Tests"'. Aborting.
System.ArgumentException: Virtual desktops are only supported on Windows 10.
   at MaxTo.Core.Commands.Window.MoveCommand.<Execute>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.Core.Commands.CommandExecutor.<Execute>d__3`2.MoveNext()
```

execute program ingredient: https://i.imgur.com/h9c3QTg.png

launch program ingredient: https://i.imgur.com/7VRfeFr.png

I am indeed using windows 10 (a non activated windows 10, but workspaces work just fine).

**Comment by vegardlarsen** [comment]
Thank you for your request. I can spot the mistake in the move command; the window title isn't "Microsoft VS Code", it is "Visual Studio Code". However, since that title changes quickly once a folder is opened, it would be better to leave the Window parameter blank, which defaults to the current foreground window, which should be VS Code immediately after starting it.

**Comment by vegardlarsen** [comment]
I am closing this issue due to lack of feedback.
