### ISSUE TITLE
Bewildering assortment of bugs

### ISSUE THREAD

**Issue by indigodreamer** [digitalcreations/MaxTo#494]
I'm currently trying out Max.To. I like the simple licensing system and the development philosophy. The basic functionality seems to work OK so I'm probably going to buy it but am having trouble with the Recipes (the most important feature which sets Max.To ahead of its competitors for me). 

There really have been a lot of strange behaviours which come and go. Having disabled every startup program I could find, and disabled all the shims I could, the most reproduceable error is found with a recipe launching Firefox. It passess an argument to Firefox telling it to open a new window and load a particular URL, then move the window. 

Firefox is now opening as expected.

If I tick the "Wait for the program to be ready" box, it doesn't move the window but throws the "Process has exited, so the requested information is not available" error message (it also sometimes throws no error, the log file claiming the recipe has been run successfully though the window was not moved). If I don't tick this box, it moves the latest window before launching Firefox. 

Recipes using Notepad are working as expected - though intermittently the program throws a "The chosen window is ignored by a compatibility shim, and cannot be moved." error even though I've disabled all the shims I could find.

Looking at the log file I see that I'm getting a "Process Server exited without explanation" error fairly consistently at system shutdown. 

I've seen other strange behaviours but more intermittently. 

Thanks. 

**System information:**
Windows 10
MaxTo Version 2.0.1

**Additional context**
Assorted log entries follow

2019-11-09 15:01:34 [Core@2.0.1.499] [Error] Process Server exited without explanation
2019-11-09 15:01:34 [UserInterface@2.0.1.499] [Information] Deactivated "MaxTo.UI.ViewModels.NotificationIconViewModel". Closed: True

2019-11-09 16:32:18 [Core@2.0.1.499] [Information] Executing recipe '"Test"' with 2 ingredients
2019-11-09 16:32:18 [Core@2.0.1.499] [Warning] Received exception from command request 2 while executing '"Test"'. Aborting.
System.ArgumentException: The chosen window is ignored by a compatibility shim, and cannot be moved.
   at MaxTo.Core.Commands.Window.MoveCommand.<Execute>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.Core.Commands.CommandExecutor.<Execute>d__3`2.MoveNext()
2019-11-09 16:32:32 [Core@2.0.1.499] [Information] Executing recipe '"Test"' with 2 ingredients
2019-11-09 16:32:32 [Core@2.0.1.499] [Warning] Received exception from command request 2 while executing '"Test"'. Aborting.
System.ArgumentException: The chosen window is ignored by a compatibility shim, and cannot be moved.
   at MaxTo.Core.Commands.Window.MoveCommand.<Execute>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.Core.Commands.CommandExecutor.<Execute>d__3`2.MoveNext()

2019-11-09 16:44:28 [UserInterface@2.0.1.499] [Information] Activated "MaxTo.UI.Components.Settings.Recipes.Index.IndexViewModel"
2019-11-09 16:44:28 [UserInterface@2.0.1.499] [Information] Activated "MaxTo.UI.Components.Settings.Recipes.RecipesViewModel"
2019-11-09 16:44:28 [UserInterface@2.0.1.499] [Error] Cannot save value from target back to source. BindingExpression:Path=ActiveItem; DataItem='SettingsViewModel' (HashCode=14198754); target element is 'HamburgerMenu' (Name=''); target property is 'SelectedItem' (type 'Object') NullReferenceException:'System.NullReferenceException: Object reference not set to an instance of an object.
   at MaxTo.UI.ViewModels.HamburgerMenuConductor`1.ChangeActiveItem(HamburgerMenuItem newItem, Boolean closePrevious)
   at Caliburn.Micro.Conductor`1.Collection.OneActive.ActivateItem(T item)
   at Caliburn.Micro.ConductorBaseWithActiveItem`1.set_ActiveItem(T value)'
2019-11-09 16:44:28 [UserInterface@2.0.1.499] [Information] Activated "MaxTo.UI.Components.Settings.SettingsViewModel"
2019-11-09 16:44:28 [UserInterface@2.0.1.499] [Information] Deactivated 

2019-11-09 16:46:01 [Core@2.0.1.499] [Information] Executing recipe '"GTD"' with 2 ingredients
2019-11-09 16:46:01 [Core@2.0.1.499] [Warning] Received exception from command request 1 while executing '"GTD"'. Aborting.
System.InvalidOperationException: Process has exited, so the requested information is not available.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_MainWindowHandle()
   at MaxTo.Core.Commands.LaunchCommand.<Execute>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.Core.Commands.CommandExecutor.<Execute>d__3`2.MoveNext()

**Comment by vegardlarsen** [comment]
Thanks for reporting this. You've received two separate errors here:

- "The chosen window is ignored by a compatibility shim, and cannot be moved."
  This means exactly what it appears to mean. I don't know why Firefox would be flagged as an ignored window, so I think you would need to provide me with the details of your recipe for me to help you out more here.
- "Process has exited, so the requested information is not available."
  We probably should improve that error message, but the cause is that launching Firefox with arguments like this will send a signal to a running Firefox instance, and then immediately exit. So waiting for it to exit won't help. However, there seems to be a timing issue here; implying that Firefox exited so quickly that MaxTo couldn't even wait for it to exit. I will be fixing this in the next release.

**Comment by vegardlarsen** [comment]
I am closing this issue as we have fixed it so the "Process has exited" error message will no longer occur. Instead, MaxTo will count that as a success, but it will indicate that the process exited quickly in the result from the command.

In regards to your Firefox issue, please supply me with the details of your recipe in a new issue, linking to this one, if this is still a problem.

This fix will be in MaxTo 2.1.0-alpha.3.
