### ISSUE TITLE
Welcome screen appears every restart

### ISSUE THREAD

**Issue by nizmow** [digitalcreations/MaxTo#500]
**Describe the bug**
I purchased, installed and configured MaxTo, but now every time I restart my PC the welcome screen appears again, and I'm forced to go through the onboarding setup every time! This includes entering my license key. Interestingly, I did define custom regions and a recipe, which persist across reboots, so some of my profile data is preserved.

**To Reproduce**
1. Install and configure MaxTo.
2. Reboot Windows.
3. MaxTo onboarding setup appears.
4. Rinse and repeat.

**System information:**
 - Windows version: 10 build 1903
 - MaxTo version 2.0.1

**Additional context**
This is a corporate machine with some GPOs locking a few things down, but I have an administrator local account. I've noticed in the log some network errors, so perhaps a firewall is blocking some things, but they don't seem relevant to the issue at hand.

I'm not sure what's relevant so I'll dump the entire log from today, it's not massive.

```
2019-11-14 09:18:44 [Core@2.0.1.499] [Information] Logger setup (online logging: True, process #8900)
2019-11-14 09:18:45 [Core@2.0.1.499] [Information] Found no specified configuration location file, using default settings location "C:\Users\n.houghton\AppData\Roaming\MaxTo"
2019-11-14 09:18:48 [Core@2.0.1.499] [Information] Logger setup (online logging: True, process #8900)
2019-11-14 09:18:48 [Core@2.0.1.499] [Warning] Shims not found at C:\Users\n.houghton\AppData\Local\MaxTo\shims.json
2019-11-14 09:19:08 [Core@2.0.1.499] [Warning] Could not update compatibility shims.
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.Core.Shims.CompatibilityShimsManager.<UpdateShimsAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.Core.Shims.CompatibilityShimsManager.<InitializeAsync>d__23.MoveNext()
2019-11-14 09:19:08 [Core@2.0.1.499] [Information] Squirrel-installed app, so rewriting CLI batch file.
2019-11-14 09:19:09 [Core@2.0.1.499] [Warning] Could not update application
System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__43`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Squirrel.FileDownloader.<DownloadUrl>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__43`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Squirrel.EasyModeMixin.<UpdateApp>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.Core.Update.UpdateService.<InitializeAsync>d__9.MoveNext()
2019-11-14 09:19:09 [Server@2.0.1.499] [Information] Logger setup (online logging: True, process #14396)
2019-11-14 09:19:09 [Core@2.0.1.499] [Information] Server up and running, client connected.
2019-11-14 09:19:10 [Core@2.0.1.499] [Information] 4 processes started
2019-11-14 09:19:10 [CompanionX64@2.0.1.499] [Information] Logger setup (online logging: True, process #14528)
2019-11-14 09:19:10 [CompanionX86@2.0.1.499] [Information] Logger setup (online logging: True, process #14492)
2019-11-14 09:19:10 [CompanionX64@2.0.1.499] [Information] Found no specified configuration location file, using default settings location "C:\Users\n.houghton\AppData\Roaming\MaxTo"
2019-11-14 09:19:10 [CompanionX86@2.0.1.499] [Information] Found no specified configuration location file, using default settings location "C:\Users\n.houghton\AppData\Roaming\MaxTo"
2019-11-14 09:19:11 [CompanionX64@2.0.1.499] [Warning] Shims not found at C:\Users\n.houghton\AppData\Local\MaxTo\shims.json
2019-11-14 09:19:11 [CompanionX86@2.0.1.499] [Warning] Shims not found at C:\Users\n.houghton\AppData\Local\MaxTo\shims.json
2019-11-14 09:19:31 [CompanionX64@2.0.1.499] [Warning] Could not update compatibility shims.
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.Core.Shims.CompatibilityShimsManager.<UpdateShimsAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.Core.Shims.CompatibilityShimsManager.<InitializeAsync>d__23.MoveNext()
2019-11-14 09:19:31 [CompanionX64@2.0.1.499] [Information] Enabled hook
2019-11-14 09:19:31 [CompanionX86@2.0.1.499] [Warning] Could not update compatibility shims.
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.Core.Shims.CompatibilityShimsManager.<UpdateShimsAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.Core.Shims.CompatibilityShimsManager.<InitializeAsync>d__23.MoveNext()
2019-11-14 09:19:31 [UserInterface@2.0.1.499] [Information] Logger setup (online logging: True, process #14564)
2019-11-14 09:19:31 [CompanionX86@2.0.1.499] [Information] Enabled hook
2019-11-14 09:19:32 [UserInterface@2.0.1.499] [Information] Activated "MaxTo.UI.ViewModels.NotificationIconViewModel"
2019-11-14 09:19:32 [UserInterface@2.0.1.499] [Information] Activated "MaxTo.UI.Components.GettingStarted.Welcome.WelcomeViewModel"
2019-11-14 09:19:32 [UserInterface@2.0.1.499] [Information] Activated "MaxTo.UI.Components.GettingStarted.WizardViewModel"
2019-11-14 09:19:57 [UserInterface@2.0.1.499] [Information] Deactivated "MaxTo.UI.Components.GettingStarted.Welcome.WelcomeViewModel". Closed: False
2019-11-14 09:19:57 [UserInterface@2.0.1.499] [Information] Activated "MaxTo.UI.Components.GettingStarted.License.LicenseViewModel"
2019-11-14 09:22:21 [UserInterface@2.0.1.499] [Information] Deactivated "MaxTo.UI.Components.GettingStarted.License.LicenseViewModel". Closed: False
2019-11-14 09:22:21 [UserInterface@2.0.1.499] [Information] Activated "MaxTo.UI.Components.GettingStarted.Regions.RegionsViewModel"
2019-11-14 09:26:56 [UserInterface@2.0.1.499] [Information] Deactivated "MaxTo.UI.Components.GettingStarted.Regions.RegionsViewModel". Closed: False
2019-11-14 09:26:57 [UserInterface@2.0.1.499] [Information] Deactivated "MaxTo.UI.Components.GettingStarted.Welcome.WelcomeViewModel". Closed: True
2019-11-14 09:26:57 [UserInterface@2.0.1.499] [Information] Deactivated "MaxTo.UI.Components.GettingStarted.License.LicenseViewModel". Closed: True
2019-11-14 09:26:57 [UserInterface@2.0.1.499] [Information] Deactivated "MaxTo.UI.Components.GettingStarted.Regions.RegionsViewModel". Closed: True
2019-11-14 09:26:57 [UserInterface@2.0.1.499] [Information] Deactivated "MaxTo.UI.Components.GettingStarted.WizardViewModel". Closed: True
2019-11-14 09:26:57 [UserInterface@2.0.1.499] [Information] Found 2 screens.
2019-11-14 09:26:58 [UserInterface@2.0.1.499] [Information] Updated regions on "3C4YP7BP807L\f09a8ea8-de86-4daa-9bc7-f555613010b4"
2019-11-14 09:26:58 [UserInterface@2.0.1.499] [Information] Updated regions on "3C4YP7A9484L\f09a8ea8-de86-4daa-9bc7-f555613010b4"
2019-11-14 09:42:53 [UserInterface@2.0.1.499] [Information] Activated "MaxTo.UI.Components.Settings.SettingsViewModel"
2019-11-14 09:42:53 [UserInterface@2.0.1.499] [Information] Activated "MaxTo.UI.Components.Settings.Recipes.Index.IndexViewModel"
2019-11-14 09:42:53 [UserInterface@2.0.1.499] [Information] Activated "MaxTo.UI.Components.Settings.Recipes.RecipesViewModel"
2019-11-14 09:44:21 [UserInterface@2.0.1.499] [Information] Found 2 screens.
2019-11-14 09:44:24 [UserInterface@2.0.1.499] [Information] Updated regions on "3C4YP7BP807L\f09a8ea8-de86-4daa-9bc7-f555613010b4"
2019-11-14 09:44:24 [UserInterface@2.0.1.499] [Information] Updated regions on "3C4YP7A9484L\f09a8ea8-de86-4daa-9bc7-f555613010b4"
2019-11-14 09:44:28 [UserInterface@2.0.1.499] [Information] Deactivated "MaxTo.UI.Components.Settings.Recipes.Index.IndexViewModel". Closed: False
2019-11-14 09:44:28 [UserInterface@2.0.1.499] [Information] Deactivated "MaxTo.UI.Components.Settings.Recipes.RecipesViewModel". Closed: False
2019-11-14 09:44:28 [UserInterface@2.0.1.499] [Information] Activated "MaxTo.UI.Components.Settings.Behavior.BehaviorViewModel"
2019-11-14 09:44:29 [UserInterface@2.0.1.499] [Information] Deactivated "MaxTo.UI.Components.Settings.Behavior.BehaviorViewModel". Closed: False
2019-11-14 09:44:29 [UserInterface@2.0.1.499] [Information] Activated "MaxTo.UI.Components.Settings.About.AboutViewModel"
2019-11-14 09:44:30 [UserInterface@2.0.1.499] [Information] Deactivated "MaxTo.UI.Components.Settings.Recipes.Index.IndexViewModel". Closed: True
2019-11-14 09:44:30 [UserInterface@2.0.1.499] [Information] Deactivated "MaxTo.UI.Components.Settings.Recipes.RecipesViewModel". Closed: True
2019-11-14 09:44:30 [UserInterface@2.0.1.499] [Information] Deactivated "MaxTo.UI.Components.Settings.Behavior.BehaviorViewModel". Closed: True
2019-11-14 09:44:30 [UserInterface@2.0.1.499] [Information] Deactivated "MaxTo.UI.Components.Settings.About.AboutViewModel". Closed: True
2019-11-14 09:44:30 [UserInterface@2.0.1.499] [Information] Deactivated "MaxTo.UI.Components.Settings.SettingsViewModel". Closed: True
```

**Comment by vegardlarsen** [comment]
@nizmow Thank you for getting in touch. I have a suspicion that this may be the same as issue #495, which I believe we have fixed in version 2.1.0-alpha.2. Can you give that a try and report back?
