### ISSUE TITLE
Bad Image error only while MaxTo is running

### ISSUE THREAD

**Issue by laurabeth** [digitalcreations/MaxTo#525]
**Describe the bug**
MaxTo causes me to be unable to open various programs. 

**To Reproduce**
1. Run MaxTo
2. Attempt to open Spotify desktop client
3. An error popup appears and cannot be dismissed except to kill the Spotify process in task manager
4. Close MaxTo
5. Attempt to open Spotify
6. Spotify runs normally

**Expected behavior**
An error popup appears and cannot be dismissed except to kill the application process in task manager

**Screenshots**
![spotify_error](https://user-images.githubusercontent.com/14044896/71732812-2ef22200-2e16-11ea-8a75-8f28c18833de.png)

![image](https://user-images.githubusercontent.com/14044896/71732957-71b3fa00-2e16-11ea-909e-5d6b0433e856.png)

**System information:**
 - Windows version: 10
 - MaxTo version 2.0 & 2.01

**Additional context**
2020-01-03 10:27:48 [Core@2.0.1.499] [Information] Logger setup (online logging: True, process #33860)
2020-01-03 10:27:49 [Core@2.0.1.499] [Information] Found no specified configuration location file, using default settings location "C:\Users\lbhayani\AppData\Roaming\MaxTo"
2020-01-03 10:27:49 [Core@2.0.1.499] [Information] Logger setup (online logging: True, process #33860)
2020-01-03 10:27:49 [Core@2.0.1.499] [Warning] Shims not found at C:\Users\lbhayani\AppData\Local\MaxTo\shims.json
2020-01-03 10:27:50 [Core@2.0.1.499] [Information] Wrote shims to "C:\Users\lbhayani\AppData\Local\MaxTo\shims.json"
2020-01-03 10:27:50 [Core@2.0.1.499] [Information] Read shims from "C:\Users\lbhayani\AppData\Local\MaxTo\shims.json"
2020-01-03 10:27:50 [Core@2.0.1.499] [Information] Squirrel-installed app, so rewriting CLI batch file.
2020-01-03 10:27:50 [Core@2.0.1.499] [Information] Squirrel: initial install "2.0.1.0".
2020-01-03 10:27:51 [Core@2.0.1.499] [Information] Logger setup (online logging: True, process #34016)
2020-01-03 10:27:51 [Core@2.0.1.499] [Information] Found no specified configuration location file, using default settings location "C:\Users\lbhayani\AppData\Roaming\MaxTo"
2020-01-03 10:27:51 [Core@2.0.1.499] [Information] Logger setup (online logging: True, process #34016)
2020-01-03 10:27:51 [Core@2.0.1.499] [Information] Read shims from "C:\Users\lbhayani\AppData\Local\MaxTo\shims.json"
2020-01-03 10:27:51 [Core@2.0.1.499] [Information] Squirrel-installed app, so rewriting CLI batch file.
2020-01-03 10:27:51 [Core@2.0.1.499] [Information] Squirrel: first run
2020-01-03 10:27:52 [Core@2.0.1.499] [Information] No updates found
2020-01-03 10:27:52 [Core@2.0.1.499] [Information] Could not find startup task, but MaxTo is set to start with Windows. Creating task.
2020-01-03 10:27:53 [Server@2.0.1.499] [Information] Logger setup (online logging: True, process #34308)
2020-01-03 10:27:53 [Core@2.0.1.499] [Information] Server up and running, client connected.
2020-01-03 10:27:53 [Core@2.0.1.499] [Information] 4 processes started
2020-01-03 10:27:53 [CompanionX86@2.0.1.499] [Information] Logger setup (online logging: True, process #34424)
2020-01-03 10:27:53 [CompanionX64@2.0.1.499] [Information] Logger setup (online logging: True, process #34432)
2020-01-03 10:27:53 [CompanionX86@2.0.1.499] [Information] Found no specified configuration location file, using default settings location "C:\Users\lbhayani\AppData\Roaming\MaxTo"
2020-01-03 10:27:53 [CompanionX64@2.0.1.499] [Information] Found no specified configuration location file, using default settings location "C:\Users\lbhayani\AppData\Roaming\MaxTo"
2020-01-03 10:27:53 [CompanionX64@2.0.1.499] [Information] Read shims from "C:\Users\lbhayani\AppData\Local\MaxTo\shims.json"
2020-01-03 10:27:54 [CompanionX64@2.0.1.499] [Information] Enabled hook
2020-01-03 10:27:54 [CompanionX86@2.0.1.499] [Information] Read shims from "C:\Users\lbhayani\AppData\Local\MaxTo\shims.json"
2020-01-03 10:27:54 [CompanionX86@2.0.1.499] [Information] Enabled hook
2020-01-03 10:27:54 [UserInterface@2.0.1.499] [Information] Logger setup (online logging: True, process #34452)
2020-01-03 10:27:54 [UserInterface@2.0.1.499] [Information] Activated "MaxTo.UI.ViewModels.NotificationIconViewModel"
2020-01-03 10:28:01 [Core@2.0.1.499] [Information] Logger setup (online logging: True, process #35240)
2020-01-03 10:28:02 [Core@2.0.1.499] [Information] MaxTo is already running. PID 34016. Exiting.
2020-01-03 10:28:11 [UserInterface@2.0.1.499] [Information] Found 2 screens.
2020-01-03 10:28:46 [UserInterface@2.0.1.499] [Information] Updated regions on "\\.\DISPLAY2"
2020-01-03 10:28:46 [UserInterface@2.0.1.499] [Information] Updated regions on "\\.\DISPLAY1"
2020-01-03 10:29:01 [UserInterface@2.0.1.499] [Information] Found 2 screens.
2020-01-03 10:30:12 [UserInterface@2.0.1.499] [Information] Updated regions on "\\.\DISPLAY2"
2020-01-03 10:30:12 [UserInterface@2.0.1.499] [Information] Updated regions on "\\.\DISPLAY1"
2020-01-03 10:49:59 [Server@2.0.1.499] [Information] Received exit message. Exiting in 250ms...
2020-01-03 10:49:59 [CompanionX86@2.0.1.499] [Information] Disabled hook because of exit
2020-01-03 10:49:59 [CompanionX64@2.0.1.499] [Information] Disabled hook because of exit
2020-01-03 10:49:59 [Core@2.0.1.499] [Information] Received exit signal, waiting for subprocesses to shut down
2020-01-03 10:49:59 [UserInterface@2.0.1.499] [Information] Deactivated "MaxTo.UI.ViewModels.NotificationIconViewModel". Closed: True
2020-01-03 10:49:59 [Server@2.0.1.499] [Warning] Lost connection to "14895bfe-9e1e-48ae-bf7f-5f68b43eb3ad"
System.IO.IOException: Pipe is broken.
   at System.IO.Pipes.PipeStream.WinIOError(Int32 errorCode)
   at System.IO.Pipes.PipeStream.BeginWriteCore(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state)
   at System.IO.Stream.<>c.<BeginEndWriteAsync>b__53_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   at System.IO.Stream.BeginEndWriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at MaxTo.Core.Communication.NamedPipeServer.<Send>d__26.MoveNext()
2020-01-03 10:49:59 [Server@2.0.1.499] [Warning] Lost connection to "42070e7d-0f18-4a81-900f-2235b26d594f"
System.IO.IOException: Pipe is broken.
   at System.IO.Pipes.PipeStream.WinIOError(Int32 errorCode)
   at System.IO.Pipes.PipeStream.BeginWriteCore(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state)
   at System.IO.Stream.<>c.<BeginEndWriteAsync>b__53_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   at System.IO.Stream.BeginEndWriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at MaxTo.Core.Communication.NamedPipeServer.<Send>d__26.MoveNext()
2020-01-03 10:49:59 [Server@2.0.1.499] [Warning] Lost connection to "c150b4c5-2b24-4200-adfb-7db33b34800f"
System.IO.IOException: Pipe is broken.
   at System.IO.Pipes.PipeStream.WinIOError(Int32 errorCode)
   at System.IO.Pipes.PipeStream.BeginWriteCore(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state)
   at System.IO.Stream.<>c.<BeginEndWriteAsync>b__53_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   at System.IO.Stream.BeginEndWriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at MaxTo.Core.Communication.NamedPipeServer.<Send>d__26.MoveNext()
2020-01-03 10:49:59 [Server@2.0.1.499] [Warning] Lost connection to "14895bfe-9e1e-48ae-bf7f-5f68b43eb3ad"
System.IO.IOException: Pipe is broken.
   at System.IO.Pipes.PipeStream.WinIOError(Int32 errorCode)
   at System.IO.Pipes.PipeStream.BeginWriteCore(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state)
   at System.IO.Stream.<>c.<BeginEndWriteAsync>b__53_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   at System.IO.Stream.BeginEndWriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at MaxTo.Core.Communication.NamedPipeServer.<Send>d__26.MoveNext()
2020-01-03 10:49:59 [Server@2.0.1.499] [Warning] Lost connection to "e7263203-9bdf-455e-af88-007af6219a90"
System.IO.IOException: Pipe is broken.
   at System.IO.Pipes.PipeStream.WinIOError(Int32 errorCode)
   at System.IO.Pipes.PipeStream.BeginWriteCore(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state)
   at System.IO.Stream.<>c.<BeginEndWriteAsync>b__53_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   at System.IO.Stream.BeginEndWriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at MaxTo.Core.Communication.NamedPipeServer.<Send>d__26.MoveNext()
2020-01-03 10:49:59 [Server@2.0.1.499] [Warning] Lost connection to "5e1beeea-1973-498a-b133-b8c62e6a5a62"
System.IO.IOException: Pipe is broken.
   at System.IO.Pipes.PipeStream.WinIOError(Int32 errorCode)
   at System.IO.Pipes.PipeStream.BeginWriteCore(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state)
   at System.IO.Stream.<>c.<BeginEndWriteAsync>b__53_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   at System.IO.Stream.BeginEndWriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at MaxTo.Core.Communication.NamedPipeServer.<Send>d__26.MoveNext()

**Comment by vegardlarsen** [comment]
Thank you for the report. Please see issue #415 for the solution to this problem. I am closing this issue as a duplicate.
