### ISSUE TITLE
"Cycle position" ingredient can crash MaxTo

### ISSUE THREAD

**Issue by thewavelength** [digitalcreations/MaxTo#576]
**Describe the bug**
I have no idea how to use the "cycle position" ingredient because it seems to be complex. What I though it does: the same as "Move window" recipe but just cycling through all regions. Because I don't know how to configure it properly (no real documentation given) I just let the default values in. MaxTo crashes once executed. See errorlog.

**To Reproduce**
1. Create recipe with "cycle position" ingredient
1. Don't change default values
1. Execute it

**Expected behavior**
I don't really know.

**System information:**
- MaxTo version: 2.1.0-beta2

**Additional context**
```
2020-05-21 14:29:22 [Core@2.1.0.660] [Information] [MaxTo.Core.Keyboard.RecipeExecutor] Executing recipe '"Cycle position"' with 1 ingredients
2020-05-21 14:29:22 [Core@2.1.0.660] [Fatal] [] Unhandled exception "ArgumentException" at "   at MaxTo.Core.Commands.CommandRegistry.CreateRequest(String name, IDictionary`2 arguments)
   at MaxTo.Core.Keyboard.RecipeExecutor.<HandleMessage>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.Core.Communication.MessageBusExtensions.<>c__DisplayClass1_0`1.<<Subscribe>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()"
System.ArgumentException: Could not convert '0' to System.Nullable`1[System.Int32] for argument Number.
Parameter name: Number ---> System.NotSupportedException: Int32Converter cannot convert from System.Int64.
   at System.ComponentModel.TypeConverter.GetConvertFromException(Object value)
   at System.ComponentModel.TypeConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at System.ComponentModel.NullableConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at MaxTo.Core.Commands.CommandRegistry.CreateRequest(String name, IDictionary`2 arguments)
   --- End of inner exception stack trace ---
   at MaxTo.Core.Commands.CommandRegistry.CreateRequest(String name, IDictionary`2 arguments)
   at MaxTo.Core.Keyboard.RecipeExecutor.<HandleMessage>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.Core.Communication.MessageBusExtensions.<>c__DisplayClass1_0`1.<<Subscribe>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
2020-05-21 14:29:22 [Core@2.1.0.660] [Fatal] [] Unhandled exception "ArgumentException" at "   at MaxTo.Core.Commands.CommandRegistry.CreateRequest(String name, IDictionary`2 arguments)
   at MaxTo.Core.Keyboard.RecipeExecutor.<HandleMessage>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.Core.Communication.MessageBusExtensions.<>c__DisplayClass1_0`1.<<Subscribe>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()"
System.ArgumentException: Could not convert '0' to System.Nullable`1[System.Int32] for argument Number.
Parameter name: Number ---> System.NotSupportedException: Int32Converter cannot convert from System.Int64.
   at System.ComponentModel.TypeConverter.GetConvertFromException(Object value)
   at System.ComponentModel.TypeConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at System.ComponentModel.NullableConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at MaxTo.Core.Commands.CommandRegistry.CreateRequest(String name, IDictionary`2 arguments)
   --- End of inner exception stack trace ---
   at MaxTo.Core.Commands.CommandRegistry.CreateRequest(String name, IDictionary`2 arguments)
   at MaxTo.Core.Keyboard.RecipeExecutor.<HandleMessage>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.Core.Communication.MessageBusExtensions.<>c__DisplayClass1_0`1.<<Subscribe>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
2020-05-21 14:29:22 [Core@2.1.0.660] [Fatal] [] Unhandled exception "ArgumentException" at "   at MaxTo.Core.Commands.CommandRegistry.CreateRequest(String name, IDictionary`2 arguments)
   at MaxTo.Core.Keyboard.RecipeExecutor.<HandleMessage>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.Core.Communication.MessageBusExtensions.<>c__DisplayClass1_0`1.<<Subscribe>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()"
System.ArgumentException: Could not convert '0' to System.Nullable`1[System.Int32] for argument Number.
Parameter name: Number ---> System.NotSupportedException: Int32Converter cannot convert from System.Int64.
   at System.ComponentModel.TypeConverter.GetConvertFromException(Object value)
   at System.ComponentModel.TypeConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at System.ComponentModel.NullableConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at MaxTo.Core.Commands.CommandRegistry.CreateRequest(String name, IDictionary`2 arguments)
   --- End of inner exception stack trace ---
   at MaxTo.Core.Commands.CommandRegistry.CreateRequest(String name, IDictionary`2 arguments)
   at MaxTo.Core.Keyboard.RecipeExecutor.<HandleMessage>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.Core.Communication.MessageBusExtensions.<>c__DisplayClass1_0`1.<<Subscribe>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
2020-05-21 14:29:22 [Core@2.1.0.660] [Fatal] [] Unhandled exception "ArgumentException" at "   at MaxTo.Core.Commands.CommandRegistry.CreateRequest(String name, IDictionary`2 arguments)
   at MaxTo.Core.Keyboard.RecipeExecutor.<HandleMessage>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.Core.Communication.MessageBusExtensions.<>c__DisplayClass1_0`1.<<Subscribe>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()"
System.ArgumentException: Could not convert '0' to System.Nullable`1[System.Int32] for argument Number.
Parameter name: Number ---> System.NotSupportedException: Int32Converter cannot convert from System.Int64.
   at System.ComponentModel.TypeConverter.GetConvertFromException(Object value)
   at System.ComponentModel.TypeConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at System.ComponentModel.NullableConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at MaxTo.Core.Commands.CommandRegistry.CreateRequest(String name, IDictionary`2 arguments)
   --- End of inner exception stack trace ---
   at MaxTo.Core.Commands.CommandRegistry.CreateRequest(String name, IDictionary`2 arguments)
   at MaxTo.Core.Keyboard.RecipeExecutor.<HandleMessage>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.Core.Communication.MessageBusExtensions.<>c__DisplayClass1_0`1.<<Subscribe>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
2020-05-21 14:29:22 [Server@2.1.0.660] [Warning] [MaxTo.Core.Communication.NamedPipeServerManager] Lost connection to "3ae7d97e-e9a1-4e2d-8cd3-1b903e59f821"
System.IO.IOException: Pipe is broken.
   at System.IO.Pipes.PipeStream.WinIOError(Int32 errorCode)
   at System.IO.Pipes.PipeStream.BeginWriteCore(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state)
   at System.IO.Stream.<>c.<BeginEndWriteAsync>b__53_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   at System.IO.Stream.BeginEndWriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at MaxTo.Core.Communication.NamedPipeServer.<Send>d__26.MoveNext()
```

**Comment by thewavelength** [comment]
As a side question then: how do I immitate "Move window" without giving a direction but rather cycle the window through all regions? Is that even possible currently with MaxTo?

**Comment by vegardlarsen** [comment]
The cycle position command is meant to work completely independent from the regions, and emulate the behavior of WinSplit Revolution.

We will have to add some sort of validation to the setup of these.

There should be default recipes set up that does this correctly.

**Comment by vegardlarsen** [comment]
I've had a look at this, and at the moment the best we can do is fix the error message so that you get notified what went wrong (you didn't set either the `Preset` or `Positions` property).

I think a good improvement we should be looking at for version 3.0, is an "all-over validator" per command, so that we could detect this kind of issue.
