### ISSUE TITLE
MaxTo.Core.exe is crashing when changing monitors

### ISSUE THREAD

**Issue by thewavelength** [digitalcreations/MaxTo#578]
**Describe the bug**
MaxTo.Core.exe is crashing when changing monitors. Sadly I only discovered it crashed on the last step. I think going from the log file time stamps it happened while being connected to or connecting to the TV via HDMI. What I did:

**To Reproduce**
1. Had MaxTo running with an external monitor connected via USB-C / Thunderbolt 3
1. Gone into hibernate mode of Windows
1. Booted up without any connected monitor
1. Connected to a TV via HDMI
1. Disconnect from TV some hours later
1. Gone to hibernate mode again
1. A day later started the laptop again with the same monitor connected as in 1.

**Expected behavior**
MaxTo should be working.

**System information:**
- Windows version: Windows 10 1909 18363.836
- MaxTo version: 2.1.0-beta2

**Additional context**
```
2020-05-22 20:51:46 [Core@2.1.0.660] [Fatal] [] Unhandled exception "NullReferenceException" at "   at MaxTo.Core.Native.Windows.MonitorExtensions.Find(IEnumerable`1 monitors, String query, Monitor currentMonitor)
   at MaxTo.Core.Recipes.Triggers.MonitorTriggerController.<>c__DisplayClass3_0`1.<ProcessTrigger>b__0(T trigger)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at MaxTo.Core.Recipes.DefaultRecipeController.<ExecuteWithFilter>d__5`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.Core.Recipes.Triggers.MonitorTriggerController.<ProcessTrigger>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()"
System.NullReferenceException: Object reference not set to an instance of an object.
   at MaxTo.Core.Native.Windows.MonitorExtensions.Find(IEnumerable`1 monitors, String query, Monitor currentMonitor)
   at MaxTo.Core.Recipes.Triggers.MonitorTriggerController.<>c__DisplayClass3_0`1.<ProcessTrigger>b__0(T trigger)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at MaxTo.Core.Recipes.DefaultRecipeController.<ExecuteWithFilter>d__5`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.Core.Recipes.Triggers.MonitorTriggerController.<ProcessTrigger>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
2020-05-22 20:51:46 [Core@2.1.0.660] [Fatal] [] Unhandled exception "NullReferenceException" at "   at MaxTo.Core.Native.Windows.MonitorExtensions.Find(IEnumerable`1 monitors, String query, Monitor currentMonitor)
   at MaxTo.Core.Recipes.Triggers.MonitorTriggerController.<>c__DisplayClass3_0`1.<ProcessTrigger>b__0(T trigger)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at MaxTo.Core.Recipes.DefaultRecipeController.<ExecuteWithFilter>d__5`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.Core.Recipes.Triggers.MonitorTriggerController.<ProcessTrigger>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()"
System.NullReferenceException: Object reference not set to an instance of an object.
   at MaxTo.Core.Native.Windows.MonitorExtensions.Find(IEnumerable`1 monitors, String query, Monitor currentMonitor)
   at MaxTo.Core.Recipes.Triggers.MonitorTriggerController.<>c__DisplayClass3_0`1.<ProcessTrigger>b__0(T trigger)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at MaxTo.Core.Recipes.DefaultRecipeController.<ExecuteWithFilter>d__5`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.Core.Recipes.Triggers.MonitorTriggerController.<ProcessTrigger>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
2020-05-22 20:51:46 [Core@2.1.0.660] [Fatal] [] Unhandled exception "NullReferenceException" at "   at MaxTo.Core.Native.Windows.MonitorExtensions.Find(IEnumerable`1 monitors, String query, Monitor currentMonitor)
   at MaxTo.Core.Recipes.Triggers.MonitorTriggerController.<>c__DisplayClass3_0`1.<ProcessTrigger>b__0(T trigger)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at MaxTo.Core.Recipes.DefaultRecipeController.<ExecuteWithFilter>d__5`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.Core.Recipes.Triggers.MonitorTriggerController.<ProcessTrigger>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()"
System.NullReferenceException: Object reference not set to an instance of an object.
   at MaxTo.Core.Native.Windows.MonitorExtensions.Find(IEnumerable`1 monitors, String query, Monitor currentMonitor)
   at MaxTo.Core.Recipes.Triggers.MonitorTriggerController.<>c__DisplayClass3_0`1.<ProcessTrigger>b__0(T trigger)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at MaxTo.Core.Recipes.DefaultRecipeController.<ExecuteWithFilter>d__5`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.Core.Recipes.Triggers.MonitorTriggerController.<ProcessTrigger>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
2020-05-22 20:51:46 [Core@2.1.0.660] [Fatal] [] Unhandled exception "NullReferenceException" at "   at MaxTo.Core.Native.Windows.MonitorExtensions.Find(IEnumerable`1 monitors, String query, Monitor currentMonitor)
   at MaxTo.Core.Recipes.Triggers.MonitorTriggerController.<>c__DisplayClass3_0`1.<ProcessTrigger>b__0(T trigger)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at MaxTo.Core.Recipes.DefaultRecipeController.<ExecuteWithFilter>d__5`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.Core.Recipes.Triggers.MonitorTriggerController.<ProcessTrigger>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()"
System.NullReferenceException: Object reference not set to an instance of an object.
   at MaxTo.Core.Native.Windows.MonitorExtensions.Find(IEnumerable`1 monitors, String query, Monitor currentMonitor)
   at MaxTo.Core.Recipes.Triggers.MonitorTriggerController.<>c__DisplayClass3_0`1.<ProcessTrigger>b__0(T trigger)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at MaxTo.Core.Recipes.DefaultRecipeController.<ExecuteWithFilter>d__5`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.Core.Recipes.Triggers.MonitorTriggerController.<ProcessTrigger>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
2020-05-22 20:51:51 [Server@2.1.0.660] [Warning] [MaxTo.Core.Communication.NamedPipeServerManager] Lost connection to "1c801b4a-cd34-495d-8736-94ca0a00beff"
System.IO.IOException: Pipe is broken.
   at System.IO.Pipes.PipeStream.WinIOError(Int32 errorCode)
   at System.IO.Pipes.PipeStream.BeginWriteCore(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state)
   at System.IO.Stream.<>c.<BeginEndWriteAsync>b__53_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   at System.IO.Stream.BeginEndWriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at MaxTo.Core.Communication.NamedPipeServer.<Send>d__26.MoveNext()
```

**Comment by vegardlarsen** [comment]
@thewavelength My guess is that somewhere in your config file is a recipe with `"monitor": null` as a parameter. If that is the case, then this will be fixed in beta.4.
