### ISSUE TITLE
Unable to move window to virtual desktop

### ISSUE THREAD

**Issue by bumbeen** [digitalcreations/MaxTo#615]
**Describe the bug**

Cannot move window to another virtual desktop.
**To Reproduce**
1. Create a recipe that moves foreground window to second virtual desktop.
**Expected behavior**

Window moves to second virtual desktop.
**Screenshots**

**System information:**
- Windows version: 1909 build 18363.1082
- MaxTo version: latest beta

**Additional context**

2020-09-16 12:05:50 [Core@2.1.0.675] [Information] [MaxTo.Core.Recipes.DefaultRecipeController] Executing recipe "startup" based on trigger "MaxTo.Core.Settings.Triggers.HotkeyTriggerConfiguration"
2020-09-16 12:05:50 [Core@2.1.0.675] [Information] [MaxTo.Core.Keyboard.RecipeExecutor] Executing recipe '"startup"' with 1 ingredients
2020-09-16 12:05:50 [Core@2.1.0.675] [Warning] [MaxTo.Core.Keyboard.RecipeExecutor] Received exception from command request 1 while executing '"startup"'. Aborting.
System.ArgumentException: Virtual desktops are only supported on Windows 10.
   at MaxTo.Core.Commands.Window.MoveCommand.<Execute>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.Core.Commands.CommandBase`2.<Execute>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.Core.Commands.CommandExecutor.<Execute>d__2.MoveNext()
2020-09-16 12:05:50 [Core@2.1.0.675] [Information] [MaxTo.Core.Recipes.DefaultRecipeController] 1 recipes was executed (0 succesfully)

![image](https://user-images.githubusercontent.com/13409987/93397414-45f66a00-f815-11ea-9dec-a2ca37746257.png)

**Comment by vegardlarsen** [comment]
@bumbeen Does this issue still persist in version 2.1.0-beta.3? You can switch to that release by setting your update channel in the app to Beta, and then restarting MaxTo twice.

There was a bug in the virtual desktop library we used for version 2.0.1, which could result in this error.

**Comment by bumbeen** [comment]
Yes this is on 2.1.0-beta.3. REcipe did not work in stable version either. Guessing something with my PC.

**Comment by vegardlarsen** [comment]
Here is the recipe I tried just now (on 2.1.0-beta.3):

```json
    {
      "name": "Test",
      "hotkey": null,
      "triggers": [
        {
          "type": "keyboard:hotkey",
          "Hotkey": "Alt+Windows+T"
        }
      ],
      "ingredients": [
        {
          "command": "window:move",
          "parameters": {
            "virtualdesktop": "1",
            "region": "center",
            "monitor": "$primary"
          }
        }
      ]
    }
```

Note that the virtual desktop number is "off by one", i.e. the first virtual desktop is numbered 0. I will be fixing that as well.

This recipe works on my machine.

There was a bug in 2.0.1 which produced the exact error message you are providing, but we've since fixed that (sorry I missed that you were running 2.1.0-beta.3 initially).

It could be a versioning issue with your version of Windows. Do you have the option of upgrading Windows to e.g. 2004?

**Comment by vegardlarsen** [comment]
I've fixed two separate issues that I discovered as part of this:

- virtual desktop numbers now start at 1, instead of 0
- the editor for the virtual desktop number didn't always store the underlying number properly
