### ISSUE TITLE
maxto service restart all of a sudden fails

### ISSUE THREAD

**Issue by mortenmoulder** [digitalcreations/MaxTo#621]
As you can see in issue #596 I've had some trouble getting MaxTo to behave normally after waking up from sleep. To combat that, I've created a task in Task Scheduler, that automatically calls `maxto service restart` when I log in. This has worked for two full weeks now, but suddenly it starts crashing with exceptions.

MaxTo version 2.1.0-beta5 and Windows 10 19041 with 2004 update.

Stacktrace found in the log files:

```
2020-10-01 00:11:03 [Core@2.1.0.694] [Information] [MaxTo.Core.Recipes.DefaultRecipeController] Executing recipe "Move window up" based on trigger "MaxTo.Core.Settings.Triggers.HotkeyTriggerConfiguration"
2020-10-01 00:11:03 [Core@2.1.0.694] [Information] [MaxTo.Core.Keyboard.RecipeExecutor] Executing recipe '"Move window up"' with 1 ingredients
2020-10-01 00:11:03 [Core@2.1.0.694] [Information] [MaxTo.Core.Keyboard.RecipeExecutor] Recipe '"Move window up"' executed successfully.
2020-10-01 00:11:03 [Core@2.1.0.694] [Information] [MaxTo.Core.Recipes.DefaultRecipeController] 1 recipes was executed (1 succesfully)
2020-10-01 00:13:09 [CompanionX64@2.1.0.694] [Information] [MaxTo.Companion.MessageHandlers.DragWindowMessageHandler] Did not receive any moving events while dragging "Emmy Awards 2011 The Office's Parody - YouTube - Google Chrome" (0x"5f1b88"), used mouse position to find region "{X=0,Y=-1080,Width=1920,Height=1080}".
2020-10-01 01:28:18 [Core@2.1.0.694] [Information] [MaxTo.Core.Recipes.DefaultRecipeController] Executing recipe "Move window down" based on trigger "MaxTo.Core.Settings.Triggers.HotkeyTriggerConfiguration"
2020-10-01 01:28:18 [Core@2.1.0.694] [Information] [MaxTo.Core.Keyboard.RecipeExecutor] Executing recipe '"Move window down"' with 1 ingredients
2020-10-01 01:28:18 [Core@2.1.0.694] [Information] [MaxTo.Core.Keyboard.RecipeExecutor] Recipe '"Move window down"' executed successfully.
2020-10-01 01:28:18 [Core@2.1.0.694] [Information] [MaxTo.Core.Recipes.DefaultRecipeController] 1 recipes was executed (1 succesfully)
2020-10-01 01:28:20 [CompanionX64@2.1.0.694] [Information] [MaxTo.Companion.MessageHandlers.DragWindowMessageHandler] Did not receive any moving events while dragging "Digital Short: The Japanese Office - SNL - YouTube - Google Chrome" (0x"5f1b88"), used mouse position to find region "{X=0,Y=0,Width=2560,Height=1400}".
2020-10-01 02:39:34 [CompanionX64@2.1.0.694] [Information] [MaxTo.Companion.MessageHandlers.DragWindowMessageHandler] Did not receive any moving events while dragging "Sound" (0x"29166c"), used mouse position to find region "{X=0,Y=-1080,Width=1920,Height=1080}".
2020-10-01 11:15:58 [CommandLine@2.1.0.694] [Information] [] Logger setup (online logging: True, process #13052)
2020-10-01 11:15:58 [CommandLine@2.1.0.694] [Information] [MaxTo.Core.Settings.DefaultConfigurationLocation] Found no specified configuration location file, using default settings location "C:\Users\USER\AppData\Roaming\MaxTo"
2020-10-01 11:16:00 [CommandLine@2.1.0.694] [Fatal] [] Unhandled exception "TimeoutException" at "   at System.IO.Pipes.NamedPipeClientStream.Connect(Int32 timeout)
   at MaxTo.Core.Communication.NamedPipeClient.<Connect>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.Core.Communication.NamedPipeMessageBusAdapter.<Connect>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.Core.Communication.MessageBusQueueingDecorator.<Connect>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.CLI.Service.ServiceRestartVerb.<Execute>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.CLI.VerbRegistry.<ExecuteActual>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.CLI.VerbRegistry.<Execute>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.CLI.Program.<Main>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.CLI.Program.<Main>(String[] args)"
System.TimeoutException: The operation has timed out.
   at System.IO.Pipes.NamedPipeClientStream.Connect(Int32 timeout)
   at MaxTo.Core.Communication.NamedPipeClient.<Connect>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.Core.Communication.NamedPipeMessageBusAdapter.<Connect>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.Core.Communication.MessageBusQueueingDecorator.<Connect>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.CLI.Service.ServiceRestartVerb.<Execute>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.CLI.VerbRegistry.<ExecuteActual>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.CLI.VerbRegistry.<Execute>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.CLI.Program.<Main>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.CLI.Program.<Main>(String[] args)
2020-10-01 11:18:31 [Core@2.1.0.694] [Information] [MaxTo.Core.Recipes.DefaultRecipeController] Executing recipe "Move window down" based on trigger "MaxTo.Core.Settings.Triggers.HotkeyTriggerConfiguration"
2020-10-01 11:18:31 [Core@2.1.0.694] [Information] [MaxTo.Core.Keyboard.RecipeExecutor] Executing recipe '"Move window down"' with 1 ingredients
2020-10-01 11:18:31 [Core@2.1.0.694] [Information] [MaxTo.Core.Keyboard.RecipeExecutor] Recipe '"Move window down"' executed successfully.
2020-10-01 11:18:31 [Core@2.1.0.694] [Information] [MaxTo.Core.Recipes.DefaultRecipeController] 1 recipes was executed (1 succesfully)
2020-10-01 11:18:32 [Core@2.1.0.694] [Information] [MaxTo.Core.Recipes.DefaultRecipeController] Executing recipe "Move window up" based on trigger "MaxTo.Core.Settings.Triggers.HotkeyTriggerConfiguration"
2020-10-01 11:18:32 [Core@2.1.0.694] [Information] [MaxTo.Core.Keyboard.RecipeExecutor] Executing recipe '"Move window up"' with 1 ingredients
2020-10-01 11:18:32 [Core@2.1.0.694] [Information] [MaxTo.Core.Keyboard.RecipeExecutor] Recipe '"Move window up"' executed successfully.
2020-10-01 11:18:32 [Core@2.1.0.694] [Information] [MaxTo.Core.Recipes.DefaultRecipeController] 1 recipes was executed (1 succesfully)
2020-10-01 11:18:40 [CommandLine@2.1.0.694] [Information] [] Logger setup (online logging: True, process #30404)
2020-10-01 11:18:40 [CommandLine@2.1.0.694] [Information] [MaxTo.Core.Settings.DefaultConfigurationLocation] Found no specified configuration location file, using default settings location "C:\Users\USER\AppData\Roaming\MaxTo"
2020-10-01 11:18:40 [Core@2.1.0.694] [Information] [MaxTo.Core.RestartService] Restarting MaxTo with arguments "--waitforexit 46056"
2020-10-01 11:18:40 [Server@2.1.0.694] [Information] [MaxTo.Server.ServerApplicationContext] Received exit message. Exiting in 250ms...
2020-10-01 11:18:40 [Server@2.1.0.694] [Warning] [MaxTo.Core.Communication.NamedPipeServerManager] Lost connection to "5bb36bde-6f32-430f-8b7a-1fa380aaf77b"
System.IO.IOException: Pipe is broken.
   at System.IO.Pipes.PipeStream.WinIOError(Int32 errorCode)
   at System.IO.Pipes.PipeStream.BeginWriteCore(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state)
   at System.IO.Stream.<>c.<BeginEndWriteAsync>b__53_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   at System.IO.Stream.BeginEndWriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at MaxTo.Core.Communication.NamedPipeServer.<Send>d__26.MoveNext()
2020-10-01 11:18:41 [Server@2.1.0.694] [Warning] [MaxTo.Core.Communication.NamedPipeServerManager] Lost connection to "595767a1-856f-4d5f-8519-0c97c376099c"
System.IO.IOException: Pipe is broken.
   at System.IO.Pipes.PipeStream.WinIOError(Int32 errorCode)
   at System.IO.Pipes.PipeStream.BeginWriteCore(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state)
   at System.IO.Stream.<>c.<BeginEndWriteAsync>b__53_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   at System.IO.Stream.BeginEndWriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at MaxTo.Core.Communication.NamedPipeServer.<Send>d__26.MoveNext()
2020-10-01 11:18:41 [UserInterface@2.1.0.694] [Information] [] Deactivated "MaxTo.UI.ViewModels.NotificationIconViewModel". Closed: True
2020-10-01 11:18:41 [Server@2.1.0.694] [Warning] [MaxTo.Core.Communication.NamedPipeServerManager] Lost connection to "ee57fcd9-21ce-4500-b653-1abaa19ccf4f"
System.IO.IOException: Pipe is broken.
   at System.IO.Pipes.PipeStream.WinIOError(Int32 errorCode)
   at System.IO.Pipes.PipeStream.BeginWriteCore(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state)
   at System.IO.Stream.<>c.<BeginEndWriteAsync>b__53_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   at System.IO.Stream.BeginEndWriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at MaxTo.Core.Communication.NamedPipeServer.<Send>d__26.MoveNext()
2020-10-01 11:18:41 [Core@2.1.0.694] [Information] [] Logger setup (online logging: True, process #13788)
2020-10-01 11:18:41 [Server@2.1.0.694] [Warning] [MaxTo.Core.Communication.NamedPipeServerManager] Lost connection to "200e9377-dfcf-4d78-846b-e1391fcf9b10"
System.IO.IOException: Pipe is broken.
   at System.IO.Pipes.PipeStream.WinIOError(Int32 errorCode)
   at System.IO.Pipes.PipeStream.BeginWriteCore(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state)
   at System.IO.Stream.<>c.<BeginEndWriteAsync>b__53_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   at System.IO.Stream.BeginEndWriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at MaxTo.Core.Communication.NamedPipeServer.<Send>d__26.MoveNext()
2020-10-01 11:18:42 [CompanionX64@2.1.0.694] [Information] [MaxTo.Companion.Hook.HookController] Disabled hook because of exit
2020-10-01 11:18:42 [CompanionX86@2.1.0.694] [Information] [MaxTo.Companion.Hook.HookController] Disabled hook because of exit
2020-10-01 11:18:43 [Core@2.1.0.694] [Information] [] Process #46056 was not running, continuing with startup.
2020-10-01 11:18:43 [Core@2.1.0.694] [Information] [MaxTo.Core.Settings.DefaultConfigurationLocation] Found no specified configuration location file, using default settings location "C:\Users\USER\AppData\Roaming\MaxTo"
2020-10-01 11:18:43 [Core@2.1.0.694] [Information] [] Logger setup (online logging: True, process #13788)
2020-10-01 11:18:43 [Core@2.1.0.694] [Information] [] Logger setup (online logging: True, process #13788)
2020-10-01 11:18:43 [Core@2.1.0.694] [Information] [MaxTo.Core.Shims.ChromiumHookBlockInitializer] Creating registry keys to unblock hooks for Chromium-based browsers: "Edge Dev, Edge Beta, Chromium, Google Chrome, Brave, Iridium".
2020-10-01 11:18:43 [Core@2.1.0.694] [Information] [] Read shims from "C:\Users\USER\AppData\Local\MaxTo\shims.json"
2020-10-01 11:18:43 [Core@2.1.0.694] [Information] [MaxTo.Core.Update.UpdateService] Squirrel-installed app, so rewriting CLI batch file.
2020-10-01 11:18:43 [Core@2.1.0.694] [Information] [MaxTo.Core.Update.UpdateService] Checking for updates.
2020-10-01 11:18:43 [Core@2.1.0.694] [Information] [MaxTo.Core.Update.UpdateService] Downloading updates to update to version "2.1.0-beta5".
2020-10-01 11:18:44 [Core@2.1.0.694] [Information] [MaxTo.Core.Update.UpdateService] Applying updates to get "2.1.0-beta5".
2020-10-01 11:18:45 [Core@2.1.0.697] [Information] [] Logger setup (online logging: True, process #29020)
```

Not sure what the problem is. To my knowledge I have not changed a single thing in Windows the last two weeks.

**Comment by vegardlarsen** [comment]
@mortenmoulder You may have been affected by an issue in version 2.1.0-beta.4, and I therefore published 2.1.0-beta.5 earlier today. At the end of your log file you can see that the version number changed, so you have just been auto updated. Can you please let me know if the problem persists with the new version?

**Comment by mortenmoulder** [comment]
@vegardlarsen Oh I didn't even see that part. I just opened MaxTo and noticed the update. It happened yesterday as well.

I will definitely keep an eye out and report back in a couple of days!

**Comment by mortenmoulder** [comment]
Still happens @vegardlarsen :(

**Comment by vegardlarsen** [comment]
Could you export the task in Task Scheduler so I can have a look at it? I suspect it could be running as the wrong user.

**Comment by mortenmoulder** [comment]
@vegardlarsen The task is not the issue. If I open cmd and type the same command, it doesn't work either:

![image](https://user-images.githubusercontent.com/1304665/94902477-80f4d080-0498-11eb-92e1-527fb7ee3234.png)

![image](https://user-images.githubusercontent.com/1304665/94902489-86eab180-0498-11eb-80e3-d32aa44dec4e.png)

![image](https://user-images.githubusercontent.com/1304665/94902506-8e11bf80-0498-11eb-8f06-1c811cd69a05.png)

3 tries to make it work. And that's consistent. It has "failed" like this for 3-4 days now. But sure, take a look:

```
<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.4" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Date>2020-09-15T13:26:54.4195549</Date>
    <Author>DESKTOP-3V10DT5\morte</Author>
    <URI>\MaxToFix</URI>
  </RegistrationInfo>
  <Triggers>
    <SessionStateChangeTrigger>
      <Enabled>true</Enabled>
      <StateChange>SessionUnlock</StateChange>
      <UserId>DESKTOP-3V10DT5\morte</UserId>
    </SessionStateChangeTrigger>
  </Triggers>
  <Principals>
    <Principal id="Author">
      <UserId>S-1-5-21-544085590-1310173255-715770846-1001</UserId>
      <LogonType>Password</LogonType>
      <RunLevel>HighestAvailable</RunLevel>
    </Principal>
  </Principals>
  <Settings>
    <MultipleInstancesPolicy>Parallel</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>true</StopIfGoingOnBatteries>
    <AllowHardTerminate>true</AllowHardTerminate>
    <StartWhenAvailable>false</StartWhenAvailable>
    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>
    <IdleSettings>
      <StopOnIdleEnd>true</StopOnIdleEnd>
      <RestartOnIdle>false</RestartOnIdle>
    </IdleSettings>
    <AllowStartOnDemand>true</AllowStartOnDemand>
    <Enabled>true</Enabled>
    <Hidden>false</Hidden>
    <RunOnlyIfIdle>false</RunOnlyIfIdle>
    <DisallowStartOnRemoteAppSession>false</DisallowStartOnRemoteAppSession>
    <UseUnifiedSchedulingEngine>true</UseUnifiedSchedulingEngine>
    <WakeToRun>false</WakeToRun>
    <ExecutionTimeLimit>PT0S</ExecutionTimeLimit>
    <Priority>7</Priority>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>MaxTo.bat</Command>
      <Arguments>service restart</Arguments>
      <WorkingDirectory>C:\Users\morte\AppData\Local\MaxTo\</WorkingDirectory>
    </Exec>
  </Actions>
</Task>
```

**Comment by mortenmoulder** [comment]
It actually fails regularly each and every time I turn on my PC after sleep now. Seems like it's the new update.

Rather annoying to say the least.

**Comment by vegardlarsen** [comment]
After having had time to look into this now, I am only able to reproduce this locally if I execute the `maxto service restart` command very quickly (e.g. before MaxTo has had a chance to fully restart and the notification area icon reappears). Then I will get this message:

![image](https://user-images.githubusercontent.com/436508/95044719-6e6cd800-06e0-11eb-8502-45d9a27f5ead.png)

My guess is that something happens to MaxTo during logon, and it may be more beneficial to run e.g. `maxto service stop` and then `maxto service start` in your task instead. Also, make sure it doesn't end up running twice at once (which could cause a race condition).

Do you have anything else in your log files that may indicate what is happening? (The current log excerpts seem to only deal with what happens after something has already stopped working)

**Comment by mortenmoulder** [comment]
Okay, I think I have something working now. It's super hacky, but it has worked for a bit. VBScript to create a hidden window.

**Action**: `Start a program`
**Program/script**: `C:\Windows\System32\cmd.exe`
**Add arguments**: `/c start wscript "C:\Users\morte\Desktop\maxtofix.vbs" >> maxtolog.txt`
**Start in**: `C:\Users\morte\`

maxtofix.vbs:

```
Dim WinScriptHost
Set WinScriptHost = CreateObject("WScript.Shell")
WinScriptHost.Run Chr(34) & "C:\Users\morte\Desktop\maxtofix.bat" & Chr(34), 0
Set WinScriptHost = Nothing
```

maxtofix.bat:

```
@echo off
C:\Users\morte\AppData\Local\MaxTo\maxto.bat service stop & C:\Users\morte\AppData\Local\MaxTo\maxto.bat service start
```
