### ISSUE TITLE
Crashes when trying to edit regions

### ISSUE THREAD

**Issue by andrejohansson** [digitalcreations/MaxTo#631]
**Describe the bug**
I have a Lenovo P52 laptop with a dock. To the dock I have connected 2 monitors, one 4k BenQ PD3200U and one older Dell monitor.

When I am not connected to the dock and use only the laptop display, I can right click the MaxTo tray and change regions.

But when I am connected to the dock and use all three monitors and try to change regions, then MaxTo crashes after I click change regions.

**To Reproduce**

1. Connect to dock (giving 3 monitors)
1. Right click Max To tray
1. Click Change regions
1. Blur rendering happens on screen 1 (laptop monitor) and perhaps 20% in on the second monitor (the rest of the monitor is clear) then MaxTo crashes.

**Expected behavior**
I expect to be able to edit the regions on each of the three monitors.

**System information:**

- Windows version: 
    
    ```
    Edition	Windows 10 Pro for Workstations
    Version	20H2
    Installed on	‎2020-‎06-‎17
    OS build	19042.572
    Experience	Windows Feature Experience Pack 120.2212.31.0
    ```
- MaxTo version: 2.1.0

**Additional context**

- Running in elevated mode
- 2 Gpus (intel integrated and nvidia quadro)
- Up 2 date drivers and system
- Log [maxto20201030.log](https://github.com/digitalcreations/MaxTo/files/5464558/maxto20201030.log)
- Config [config.json.txt](https://github.com/digitalcreations/MaxTo/files/5464561/config.json.txt)

**Comment by vegardlarsen** [comment]
Thank you for your comment. It appears that the relevant parts from the log file is this:

```
2020-10-30 11:39:59 [UserInterface@2.1.0.704] [Fatal] [] Unhandled exception "COMException" at "   at System.Windows.Media.Composition.DUCE.Channel.SyncFlush()
   at System.Windows.Media.MediaContext.CompleteRender()
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)"
System.Runtime.InteropServices.COMException (0x88980406): UCEERR_RENDERTHREADFAILURE (Exception from HRESULT: 0x88980406)
   at System.Windows.Media.Composition.DUCE.Channel.SyncFlush()
   at System.Windows.Media.MediaContext.CompleteRender()
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
```

There seems to be an [open bug in WPF producing this kind of error](https://github.com/dotnet/wpf/issues/3100).

[Quoting](https://github.com/dotnet/wpf/issues/3100#issuecomment-673569758) @BrannonKing from that thread:

> There's something wrong with .NET Framework 4.8.4200.0 -- that version specifically that came out just recently and was applied via Windows Update over the last few days. That's causing complete breakage of HostVisual, throwing this COMException error. The specific patch is TBD. If you're on Windows build 2004, you can uninstall KB4569745 to repair the issue (and go back to Framework version 4180). If you have KB4562900 installed, you may have success removing that update.

Can you try that first?

The error code `UCEERR_RENDERTHREADFAILURE ` could also indicate that something goes wrong while rendering those windows, and I suspect it could be related to your video card driver (based on [this](https://social.msdn.microsoft.com/Forums/vstudio/en-US/0b16ab5a-6dcd-4c13-a859-8425f125d497/uceerrrenderthreadfailure-at)). Can you check the version of your video card driver and then try updating the driver afterwards?

**Comment by andrejohansson** [comment]
Gathering my versions in the system and double checking that everything is up2date did not help. Still the same error. :-(

### Windows update
All patches and updates installed

Edition	Windows 10 Pro for Workstations
Version	20H2
Installed on	‎2020-‎06-‎17
OS build	19042.610
Experience	Windows Feature Experience Pack 120.2212.31.0

![image](https://user-images.githubusercontent.com/2828428/97720031-113e2980-1ac8-11eb-988a-08021305baea.png)


### .NET framework
Framework is up2date, downloading the latest .NET framework from https://dotnet.microsoft.com/download says "you already have the latest version".
```
❯ .\DotNetVersions.exe
Currently installed "classic" .NET Versions in the system:
2.0.50727.4927 Service Pack 2
3.0.30729.4926 Service Pack 2
3.5.30729.4926 Service Pack 1
4.0.0.0
4.8.04084 <-- This is my latest, but in the comment you posted they seem to be on an even newer .NET framework (4.8.4200.0)? 
```

### Intel® UHD Graphics P630
Driver is up2date
```
Provider  Intel Corporation
Version  27.20.100.8853
Date  10/14/2020
```

### NVIDIA Quadro P2000
Driver is up2date
```
Provider  NVIDIA
Version  27.21.14.5257
Date  10/22/2020
```

### KB updates
Neither KB4569745, KB4562900 exist on my system.

![image](https://user-images.githubusercontent.com/2828428/97719906-ebb12000-1ac7-11eb-952a-c1ae672a82c8.png)

**Comment by vegardlarsen** [comment]
Can you try uninstalling .NET Framework 4.8 and [installing 4.7.2 instead](https://dotnet.microsoft.com/download/dotnet-framework/net472)?

**Comment by andrejohansson** [comment]
Unfortunately I don't have the possibility to do that right now due to other projects.

According to: https://support.microsoft.com/en-us/help/4569749/kb4569749-cumulative-update-for-net-framework

I tried to add ``AppContextSwitchOverrides`` to the *.config files in the folder: ``C:\Users\AndréJohansson\AppData\Local\MaxTo\app-2.1.0`` but it did nothelp either.


```xml
<?xml version="1.0"?>
<configuration>
    <runtime>
        <AppContextSwitchOverrides value="Switch.System.Windows.Media.HostVisual.DisconnectsOnWrongThread=true"/>
    </runtime>
</configuration>
```

**Comment by vegardlarsen** [comment]
@andrejohansson Could you try to use the registry version of the fix instead? (Note that you need to place it in two places)

I am somewhat concerned that the .config file could sometimes not be loaded.

**Comment by vegardlarsen** [comment]
@andrejohansson Any updates on this on your end?
