### ISSUE TITLE
Using self-made presets with regions:cycle crashes

### ISSUE THREAD

**Issue by vegardlarsen** [digitalcreations/MaxTo#695]
**Describe the bug**
MaxTo crashes when executing the below recipe

```json
{
  "name": "Cycle Presets",
  "hotkey": null,
  "triggers": [
    {
      "type": "keyboard:hotkey",
      "Hotkey": "Control+Windows+Z"
    }
  ],
  "ingredients": [
    {
      "command": "regions:cycle",
      "parameters": {
        "monitor": "$current",
        "presets": "Two-way vertical,Ultra-wide three-way,Four Screens"
      }
    }
  ]
}
```

**To Reproduce**

1. Import the recipe above (ensure you have the "Four Screens" preset).
2. Run it.
3. `NullReferenceException`.

**Expected behavior**
No crash.

**System information:**
- Windows version: 10 20H2 (19042.746)
- MaxTo version: 2.1.5

**Additional context**

Stack trace from log:

This produces the following stack trace:

```
[MaxTo.Core.Keyboard.RecipeExecutor] Executing recipe '"Cycle Presets"' with 1 ingredients
2021-01-22 19:42:41 [Core@2.1.5.732] [Warning] [MaxTo.Core.Keyboard.RecipeExecutor] Received exception from command request 1 while executing '"Cycle Presets"'. Aborting.
System.NullReferenceException: Object reference not set to an instance of an object.
   at MaxTo.Core.Commands.Regions.CycleCommand.<Execute>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.Core.Commands.CommandBase`2.<Execute>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.Core.Commands.CommandExecutor.<Execute>d__2.MoveNext()
```

**Comment by vegardlarsen** [comment]
The cause has been located, fixed, and will be released in version 2.2.0.
