### ISSUE TITLE
Crash when running Dashlane

### ISSUE THREAD

**Issue by vegardlarsen** [digitalcreations/MaxTo#703]
**Describe the bug**

MaxTo.Companion.x64 crashes at seemingly random times when running Dashlane.

**System information:**
- Windows version: 10 20H2 19042.804
- MaxTo version: 2.1.5

**Additional context**

```
System.ArgumentException: Process with an Id of 32776 is not running.
   at System.Diagnostics.Process.GetProcessById(Int32 processId, String machineName)
   at MaxTo.Core.Native.Windows.SystemWindow.get_Process()
   at MaxTo.Core.Shims.CompatibilityShimsManager.<>c__DisplayClass28_0.<HasFlag>b__1(String p)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at System.Linq.Enumerable.<>c__DisplayClass6_0`1.<CombinePredicates>b__0(TSource x)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at MaxTo.Core.Shims.CompatibilityShimsManager.HasFlag(ISystemWindow window, String flag, Func`2 predicate)
   at MaxTo.Companion.MessageHandlers.MaximizeWindowMessageHandler.ActInternal(String name, Message message)
   at MaxTo.Companion.MessageHandlers.WindowMessageHandlerBase.Act(Message message)
   at MaxTo.Companion.MessageHandlers.WindowMessageHandlerDispatcher.Dispatch(Message message)
   at MaxTo.Companion.Hook.HookController.MessageSourceOnWindowMessage(Object sender, Message message)
   at MaxTo.Core.Native.HiddenWindowMessageSource.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by vegardlarsen** [comment]
This issue has been fixed, and will be in 2.2.0-beta.2.
