### ISSUE TITLE
E_ACCESSDENIED when moving window to virtual desktop

### ISSUE THREAD

**Issue by vegardlarsen** [digitalcreations/MaxTo#704]
**Describe the bug**

Recipes that move windows to other virtual desktops fails with a cryptic error message.

**System information:**
- MaxTo version: 2.2.0-beta.1

**Additional context**

```
Received exception from command request 1 while executing '"Move to Virtual Desktop #2"'. Aborting.
System.UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
   at MaxTo.Core.Native.VirtualDesktops.Interop.IVirtualDesktopManager.MoveWindowToDesktop(IntPtr topLevelWindow, Guid& desktopId)
   at MaxTo.Core.Commands.Window.MoveCommand.<Execute>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.Core.Commands.CommandBase`2.<Execute>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.Core.Commands.CommandExecutor.<Execute>d__2.MoveNext()
```

**Comment by vegardlarsen** [comment]
This issue has been fixed for 2.2.0-beta.2.
