### ISSUE TITLE
MaxTo crashing when trying to change regions

### ISSUE THREAD

**Issue by RookieKiwi** [digitalcreations/MaxTo#714]
Hey All,
MaxTo was running perfectly until i rebooted, now whenever i try to change regions it crashes, i reinstalled and deleted the AppData folders but its still crashing, Logs attached, running Windows 10 with 3 monitors and it was working perfectly until reboot.

Windows version: 20H2 19042.870
Maxto version: latest

Steps to reproduce:
just start Maxto and click on the tray icon and it crashes

Config.json:
`
{
  "$schema": "https://maxto.net/config.schema.json",
  "language": null,
  "startup": {
    "startOnLogon": true,
    "runElevated": true
  },
  "updates": {
    "enabled": true,
    "channel": "Stable"
  },
  "behavior": {
    "snap": {
      "to": [
        "Screen",
        "Window"
      ],
      "distance": 10
    },
    "transparentWindowsWhenMoving": true,
    "passiveMode": false
  },
  "shims": {
    "toggled": {}
  },
  "license": {
    "firstStart": "2021-04-02T19:36:23.337312Z"
  },
  "recipes": [
    {
      "name": "Move window left",
      "hotkey": null,
      "triggers": [
        {
          "type": "keyboard:hotkey",
          "Hotkey": "Windows+Left"
        }
      ],
      "ingredients": [
        {
          "command": "window:move",
          "parameters": {
            "direction": "Left"
          }
        }
      ]
    },
    {
      "name": "Move window up",
      "hotkey": null,
      "triggers": [
        {
          "type": "keyboard:hotkey",
          "Hotkey": "Windows+Up"
        }
      ],
      "ingredients": [
        {
          "command": "window:move",
          "parameters": {
            "direction": "Up"
          }
        }
      ]
    },
    {
      "name": "Move window right",
      "hotkey": null,
      "triggers": [
        {
          "type": "keyboard:hotkey",
          "Hotkey": "Windows+Right"
        }
      ],
      "ingredients": [
        {
          "command": "window:move",
          "parameters": {
            "direction": "Right"
          }
        }
      ]
    },
    {
      "name": "Move window down",
      "hotkey": null,
      "triggers": [
        {
          "type": "keyboard:hotkey",
          "Hotkey": "Windows+Down"
        }
      ],
      "ingredients": [
        {
          "command": "window:move",
          "parameters": {
            "direction": "Down"
          }
        }
      ]
    },
    {
      "name": "Swap window left",
      "hotkey": null,
      "triggers": [
        {
          "type": "keyboard:hotkey",
          "Hotkey": "Windows+Alt+Left"
        }
      ],
      "ingredients": [
        {
          "command": "window:move",
          "parameters": {
            "direction": "Left",
            "swap": true
          }
        }
      ]
    },
    {
      "name": "Swap window up",
      "hotkey": null,
      "triggers": [
        {
          "type": "keyboard:hotkey",
          "Hotkey": "Windows+Alt+Up"
        }
      ],
      "ingredients": [
        {
          "command": "window:move",
          "parameters": {
            "direction": "Up",
            "swap": true
          }
        }
      ]
    },
    {
      "name": "Swap window right",
      "hotkey": null,
      "triggers": [
        {
          "type": "keyboard:hotkey",
          "Hotkey": "Windows+Alt+Right"
        }
      ],
      "ingredients": [
        {
          "command": "window:move",
          "parameters": {
            "direction": "Right",
            "swap": true
          }
        }
      ]
    },
    {
      "name": "Swap window down",
      "hotkey": null,
      "triggers": [
        {
          "type": "keyboard:hotkey",
          "Hotkey": "Windows+Alt+Down"
        }
      ],
      "ingredients": [
        {
          "command": "window:move",
          "parameters": {
            "direction": "Down",
            "swap": true
          }
        }
      ]
    },
    {
      "name": "Center window",
      "hotkey": null,
      "triggers": [
        {
          "type": "keyboard:hotkey",
          "Hotkey": "Windows+Alt+C"
        }
      ],
      "ingredients": [
        {
          "command": "window:center",
          "parameters": {}
        }
      ]
    },
    {
      "name": "Maximize to monitor",
      "hotkey": null,
      "triggers": [
        {
          "type": "keyboard:hotkey",
          "Hotkey": "Windows+Alt+M"
        }
      ],
      "ingredients": [
        {
          "command": "window:maximize",
          "parameters": {}
        }
      ]
    },
    {
      "name": "Place top left on grid",
      "hotkey": null,
      "triggers": [
        {
          "type": "keyboard:hotkey",
          "Hotkey": "Ctrl+Alt+NumPad7"
        }
      ],
      "ingredients": [
        {
          "command": "window:cycle-position",
          "parameters": {
            "preset": "TopLeft"
          }
        }
      ]
    },
    {
      "name": "Place top on grid",
      "hotkey": null,
      "triggers": [
        {
          "type": "keyboard:hotkey",
          "Hotkey": "Ctrl+Alt+NumPad8"
        }
      ],
      "ingredients": [
        {
          "command": "window:cycle-position",
          "parameters": {
            "preset": "Top"
          }
        }
      ]
    },
    {
      "name": "Place top right on grid",
      "hotkey": null,
      "triggers": [
        {
          "type": "keyboard:hotkey",
          "Hotkey": "Ctrl+Alt+NumPad9"
        }
      ],
      "ingredients": [
        {
          "command": "window:cycle-position",
          "parameters": {
            "preset": "TopRight"
          }
        }
      ]
    },
    {
      "name": "Place left on grid",
      "hotkey": null,
      "triggers": [
        {
          "type": "keyboard:hotkey",
          "Hotkey": "Ctrl+Alt+NumPad4"
        }
      ],
      "ingredients": [
        {
          "command": "window:cycle-position",
          "parameters": {
            "preset": "Left"
          }
        }
      ]
    },
    {
      "name": "Place center on grid",
      "hotkey": null,
      "triggers": [
        {
          "type": "keyboard:hotkey",
          "Hotkey": "Ctrl+Alt+NumPad5"
        }
      ],
      "ingredients": [
        {
          "command": "window:cycle-position",
          "parameters": {
            "preset": "Center"
          }
        }
      ]
    },
    {
      "name": "Place right on grid",
      "hotkey": null,
      "triggers": [
        {
          "type": "keyboard:hotkey",
          "Hotkey": "Ctrl+Alt+NumPad6"
        }
      ],
      "ingredients": [
        {
          "command": "window:cycle-position",
          "parameters": {
            "preset": "Right"
          }
        }
      ]
    },
    {
      "name": "Place bottom left on grid",
      "hotkey": null,
      "triggers": [
        {
          "type": "keyboard:hotkey",
          "Hotkey": "Ctrl+Alt+NumPad1"
        }
      ],
      "ingredients": [
        {
          "command": "window:cycle-position",
          "parameters": {
            "preset": "BottomLeft"
          }
        }
      ]
    },
    {
      "name": "Place bottom on grid",
      "hotkey": null,
      "triggers": [
        {
          "type": "keyboard:hotkey",
          "Hotkey": "Ctrl+Alt+NumPad2"
        }
      ],
      "ingredients": [
        {
          "command": "window:cycle-position",
          "parameters": {
            "preset": "Bottom"
          }
        }
      ]
    },
    {
      "name": "Place bottom right on grid",
      "hotkey": null,
      "triggers": [
        {
          "type": "keyboard:hotkey",
          "Hotkey": "Ctrl+Alt+NumPad3"
        }
      ],
      "ingredients": [
        {
          "command": "window:cycle-position",
          "parameters": {
            "preset": "BottomRight"
          }
        }
      ]
    },
    {
      "name": "Change regions",
      "hotkey": null,
      "triggers": [
        {
          "type": "keyboard:hotkey",
          "Hotkey": "Windows+Control+R"
        }
      ],
      "ingredients": [
        {
          "command": "ui:open",
          "parameters": {
            "window": "ChangeRegions"
          }
        }
      ]
    },
    {
      "name": "Open settings window",
      "hotkey": null,
      "triggers": [
        {
          "type": "keyboard:hotkey",
          "Hotkey": "Windows+Control+T"
        }
      ],
      "ingredients": [
        {
          "command": "ui:open",
          "parameters": {
            "window": "Settings"
          }
        }
      ]
    },
    {
      "name": "Change regions on new virtual desktops",
      "hotkey": null,
      "triggers": [
        {
          "type": "virtualdesktop:created"
        }
      ],
      "ingredients": [
        {
          "command": "ui:open",
          "parameters": {
            "window": "ChangeRegions"
          }
        }
      ]
    },
    {
      "name": "Move window to next virtual desktop",
      "hotkey": null,
      "triggers": [
        {
          "type": "keyboard:hotkey",
          "Hotkey": "Windows+Control+Alt+Right"
        }
      ],
      "ingredients": [
        {
          "command": "window:move",
          "parameters": {
            "virtualdesktop": "$next"
          }
        }
      ]
    },
    {
      "name": "Move window to previous virtual desktop",
      "hotkey": null,
      "triggers": [
        {
          "type": "keyboard:hotkey",
          "Hotkey": "Windows+Control+Alt+Left"
        }
      ],
      "ingredients": [
        {
          "command": "window:move",
          "parameters": {
            "virtualdesktop": "$previous"
          }
        }
      ]
    },
    {
      "name": "Expand left",
      "hotkey": null,
      "triggers": [
        {
          "type": "keyboard:hotkey",
          "Hotkey": "Windows+Control+NumPad4"
        }
      ],
      "ingredients": [
        {
          "command": "window:expand",
          "parameters": {
            "edge": "Left",
            "to": "Window, Region, Screen"
          }
        }
      ]
    },
    {
      "name": "Expand right",
      "hotkey": null,
      "triggers": [
        {
          "type": "keyboard:hotkey",
          "Hotkey": "Windows+Control+NumPad6"
        }
      ],
      "ingredients": [
        {
          "command": "window:expand",
          "parameters": {
            "edge": "Right",
            "to": "Window, Region, Screen"
          }
        }
      ]
    },
    {
      "name": "Expand up",
      "hotkey": null,
      "triggers": [
        {
          "type": "keyboard:hotkey",
          "Hotkey": "Windows+Control+NumPad8"
        }
      ],
      "ingredients": [
        {
          "command": "window:expand",
          "parameters": {
            "edge": "Top",
            "to": "Window, Region, Screen"
          }
        }
      ]
    },
    {
      "name": "Expand down",
      "hotkey": null,
      "triggers": [
        {
          "type": "keyboard:hotkey",
          "Hotkey": "Windows+Control+NumPad2"
        }
      ],
      "ingredients": [
        {
          "command": "window:expand",
          "parameters": {
            "edge": "Bottom",
            "to": "Window, Region, Screen"
          }
        }
      ]
    },
    {
      "name": "Contract left",
      "hotkey": null,
      "triggers": [
        {
          "type": "keyboard:hotkey",
          "Hotkey": "Windows+Alt+NumPad4"
        }
      ],
      "ingredients": [
        {
          "command": "window:contract",
          "parameters": {
            "edge": "Right",
            "to": "Window, Region, Screen"
          }
        }
      ]
    },
    {
      "name": "Contract right",
      "hotkey": null,
      "triggers": [
        {
          "type": "keyboard:hotkey",
          "Hotkey": "Windows+Alt+NumPad6"
        }
      ],
      "ingredients": [
        {
          "command": "window:contract",
          "parameters": {
            "edge": "Left",
            "to": "Window, Region, Screen"
          }
        }
      ]
    },
    {
      "name": "Contract up",
      "hotkey": null,
      "triggers": [
        {
          "type": "keyboard:hotkey",
          "Hotkey": "Windows+Alt+NumPad8"
        }
      ],
      "ingredients": [
        {
          "command": "window:contract",
          "parameters": {
            "edge": "Bottom",
            "to": "Window, Region, Screen"
          }
        }
      ]
    },
    {
      "name": "Contract down",
      "hotkey": null,
      "triggers": [
        {
          "type": "keyboard:hotkey",
          "Hotkey": "Windows+Alt+NumPad2"
        }
      ],
      "ingredients": [
        {
          "command": "window:contract",
          "parameters": {
            "edge": "Top",
            "to": "Window, Region, Screen"
          }
        }
      ]
    }
  ],
  "monitor": {
    "idSelection": "SerialNumber",
    "virtualDesktop": true
  },
  "errorReporting": {
    "anonymityLevel": "MachineIdentifier",
    "enabled": true,
    "logLevel": "Information"
  },
  "presets": [
    {
      "type": "split",
      "splits": {
        "orientation": "Vertical",
        "distance": 0.5,
        "child1": null,
        "child2": null
      },
      "name": "Two-way vertical"
    },
    {
      "type": "split",
      "splits": {
        "orientation": "Horizontal",
        "distance": 0.5,
        "child1": null,
        "child2": null
      },
      "name": "Two-way horizontal"
    },
    {
      "type": "split",
      "splits": {
        "orientation": "Horizontal",
        "distance": 0.5,
        "child1": {
          "orientation": "Vertical",
          "distance": 0.5,
          "child1": null,
          "child2": null
        },
        "child2": {
          "orientation": "Vertical",
          "distance": 0.5,
          "child1": null,
          "child2": null
        }
      },
      "name": "Quarters"
    },
    {
      "type": "split",
      "splits": {
        "orientation": "Horizontal",
        "distance": 0.25,
        "child1": null,
        "child2": {
          "orientation": "Horizontal",
          "distance": 0.6666667,
          "child1": null,
          "child2": null
        }
      },
      "name": "Ultra-wide three-way"
    },
    {
      "type": "split",
      "splits": {
        "orientation": "Horizontal",
        "distance": 0.25,
        "child1": {
          "orientation": "Vertical",
          "distance": 0.5,
          "child1": null,
          "child2": null
        },
        "child2": null
      },
      "name": "Two on the left"
    },
    {
      "type": "split",
      "splits": {
        "orientation": "Horizontal",
        "distance": 0.75,
        "child1": null,
        "child2": {
          "orientation": "Vertical",
          "distance": 0.5,
          "child1": null,
          "child2": null
        }
      },
      "name": "Two on the right"
    }
  ]
}
`

error log:

`
2021-04-03 08:43:07 [Core@2.1.5.732] [Information] [] Logger setup (online logging: True, process #11964)
2021-04-03 08:43:07 [Core@2.1.5.732] [Information] [MaxTo.Core.Settings.DefaultConfigurationLocation] Found no specified configuration location file, using default settings location "C:\Users\James Laptop\AppData\Roaming\MaxTo"
2021-04-03 08:43:07 [Core@2.1.5.732] [Information] [] Logger setup (online logging: True, process #11964)
2021-04-03 08:43:07 [Core@2.1.5.732] [Information] [] Logger setup (online logging: True, process #11964)
2021-04-03 08:43:07 [Core@2.1.5.732] [Information] [MaxTo.Core.Shims.ChromiumHookBlockInitializer] Creating registry keys to unblock hooks for Chromium-based browsers: "Edge Dev, Edge Beta, Chromium, Google Chrome, Brave, Iridium".
2021-04-03 08:43:08 [Core@2.1.5.732] [Information] [] Read shims from "C:\Users\James Laptop\AppData\Local\MaxTo\shims.json"
2021-04-03 08:43:08 [Core@2.1.5.732] [Information] [MaxTo.Core.Update.UpdateService] Squirrel-installed app, so rewriting CLI batch file.
2021-04-03 08:43:08 [Core@2.1.5.732] [Information] [MaxTo.Core.Update.UpdateService] Checking for updates.
2021-04-03 08:43:09 [Core@2.1.5.732] [Information] [MaxTo.Core.Update.UpdateService] Found no new updates.
2021-04-03 08:43:09 [Core@2.1.5.732] [Information] [MaxTo.Core.Update.UpdateService] No updates found
2021-04-03 08:43:10 [Server@2.1.5.732] [Information] [] Logger setup (online logging: True, process #12852)
2021-04-03 08:43:10 [Core@2.1.5.732] [Information] [] Server up and running, client connected.
2021-04-03 08:43:10 [Core@2.1.5.732] [Information] [MaxTo.Core.Bootstrapper] 4 processes started
2021-04-03 08:43:10 [CompanionX64@2.1.5.732] [Information] [] Logger setup (online logging: True, process #11696)
2021-04-03 08:43:10 [CompanionX86@2.1.5.732] [Information] [] Logger setup (online logging: True, process #13264)
2021-04-03 08:43:10 [CompanionX64@2.1.5.732] [Information] [MaxTo.Core.Settings.DefaultConfigurationLocation] Found no specified configuration location file, using default settings location "C:\Users\James Laptop\AppData\Roaming\MaxTo"
2021-04-03 08:43:10 [CompanionX86@2.1.5.732] [Information] [MaxTo.Core.Settings.DefaultConfigurationLocation] Found no specified configuration location file, using default settings location "C:\Users\James Laptop\AppData\Roaming\MaxTo"
2021-04-03 08:43:11 [CompanionX64@2.1.5.732] [Information] [] Read shims from "C:\Users\James Laptop\AppData\Local\MaxTo\shims.json"
2021-04-03 08:43:11 [CompanionX64@2.1.5.732] [Information] [MaxTo.Companion.Hook.HookController] Enabled hook
2021-04-03 08:43:11 [CompanionX86@2.1.5.732] [Information] [] Read shims from "C:\Users\James Laptop\AppData\Local\MaxTo\shims.json"
2021-04-03 08:43:12 [CompanionX86@2.1.5.732] [Information] [MaxTo.Companion.Hook.HookController] Enabled hook
2021-04-03 08:43:12 [UserInterface@2.1.5.732] [Information] [] Logger setup (online logging: True, process #10184)
2021-04-03 08:43:12 [UserInterface@2.1.5.732] [Information] [] Activated "MaxTo.UI.ViewModels.NotificationIconViewModel"
2021-04-03 08:43:23 [UserInterface@2.1.5.732] [Information] [MaxTo.UI.ViewModels.SetRegionsWindowManager] Found 3 screens.
2021-04-03 08:43:23 [UserInterface@2.1.5.732] [Fatal] [] Unhandled exception "COMException" at "   at System.Windows.Media.Composition.DUCE.Channel.SyncFlush()
   at System.Windows.Media.MediaContext.CompleteRender()
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)"
System.Runtime.InteropServices.COMException (0x88980406): UCEERR_RENDERTHREADFAILURE (Exception from HRESULT: 0x88980406)
   at System.Windows.Media.Composition.DUCE.Channel.SyncFlush()
   at System.Windows.Media.MediaContext.CompleteRender()
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
2021-04-03 08:43:31 [Server@2.1.5.732] [Warning] [MaxTo.Core.Communication.NamedPipeServerManager] Lost connection to "1ff6a592-9573-44b6-a177-85e0a566a650"
System.IO.IOException: Pipe is broken.
   at System.IO.Pipes.PipeStream.WinIOError(Int32 errorCode)
   at System.IO.Pipes.PipeStream.BeginWriteCore(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state)
   at System.IO.Stream.<>c.<BeginEndWriteAsync>b__53_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   at System.IO.Stream.BeginEndWriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at MaxTo.Core.Communication.NamedPipeServer.<Send>d__26.MoveNext()
2021-04-03 08:43:31 [Core@2.1.5.732] [Error] [MaxTo.Core.Bootstrapper] Process UserInterface exited without explanation

`

**Comment by RookieKiwi** [comment]
Actually i upgraded to the beta version and it appears to of resolved the issue.
