### ISSUE TITLE
NullReferenceException in DefaultRecipeController

### ISSUE THREAD

**Issue by vegardlarsen** [digitalcreations/MaxTo#771]
**Describe the bug**
MaxTo crashes.

**Additional context**

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at MaxTo.Core.Recipes.DefaultRecipeController.<ExecuteInternal>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at MaxTo.Core.Recipes.DefaultRecipeController.<ExecuteWithFilter>d__6`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.Core.Keyboard.HotkeyRegistrationService.<HotkeyPressed>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

**Comment by vegardlarsen** [comment]
I'm afraid to write this, but my own bug report is not enough to actually track down this crash. So, bad reporting from me there.
