### ISSUE TITLE
Crash when firewall denies access to web

### ISSUE THREAD

**Issue by byrongits** [digitalcreations/MaxTo#786]
**Describe the bug**

Why does the program try to connect to Amazonaws.com or Cloudflarenet and why does it quit when it is denied access?

Program attempts to communicate to the following IPs:

Amazon
********************
34.206.29.100
52.204.118.70
52.200.145.6
54.85.22.24

CLOUDFLARENET
********************
104.21.79.163
172.67.146.151

**To Reproduce**

Enable any firewall program with logging enabled to view IPs and servives contacted.

**Expected behavior**
Expected behavior is to run the app without needing internet access or prevent the applicatin to run when blocking such a request.  

**Screenshots**

**System information:**
- Windows version: 
Windows 10 Version 21H2 (OS Build 19044.1645)
- MaxTo version: 
MaxTo.Core
2.2.1.772

**Additional context**

--------------
config

```
{
  "$schema": "https://maxto.net/config.schema.json",
  "language": null,
  "startup": {
    "startOnLogon": false,
    "runElevated": true
  },
  "updates": {
    "enabled": false,
    "channel": "Stable"
  },
  "behavior": {
    "snap": {
      "to": [
        "Window",
        "Screen"
      ],
      "distance": 10
    },
    "transparentWindowsWhenMoving": false,
    "passiveMode": false
  },
  "shims": {
    "toggled": {}
  },
  "license": {
    "firstStart": "2020-03-20T00:30:24.965364Z"
  },
  "recipes": [
    {
      "enabled": true,
      "id": "__builtin.move.left"
    },
    {
      "enabled": true,
      "id": "__builtin.move.up"
    },
    {
      "enabled": true,
      "id": "__builtin.move.right"
    },
    {
      "enabled": true,
      "id": "__builtin.move.down"
    },
    {
      "enabled": true,
      "id": "__builtin.swap.left"
    },
    {
      "enabled": true,
      "id": "__builtin.swap.up"
    },
    {
      "enabled": true,
      "id": "__builtin.swap.right"
    },
    {
      "enabled": true,
      "id": "__builtin.swap.down"
    },
    {
      "enabled": true,
      "id": "__builtin.center"
    },
    {
      "enabled": true,
      "id": "__builtin.maximize"
    }
  ],
  "monitor": {
    "idSelection": "Numbered",
    "virtualDesktop": false
  },
  "errorReporting": {
    "anonymityLevel": "Anonymous",
    "enabled": false,
    "logLevel": "Information"
  },
  "presets": [
    { 
````
-----------------
MaxTo crashes

```
   at MaxTo.UI.App.Main()"
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissions 104.21.79.163:443
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.Core.Shims.CompatibilityShimsManager.<UpdateShimsAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.UI.Components.Settings.Compatibility.Index.IndexViewModel.<Update>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at MaxTo.UI.App.Main()
2022-04-27 17:47:57 [Core@2.2.1.772] [Error] [MaxTo.Core.Bootstrapper] Process UserInterface exited without explanation
2022-04-27 17:47:57 [Server@2.2.1.772] [Warning] [MaxTo.Core.Communication.NamedPipeServerManager] Lost connection to "ded432b6-86d7-47e9-b762-41e968ad5fa1"
System.IO.IOException: Pipe is broken.
   at System.IO.Pipes.PipeStream.WinIOError(Int32 errorCode)
   at System.IO.Pipes.PipeStream.BeginWriteCore(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state)
   at System.IO.Stream.<>c.<BeginEndWriteAsync>b__53_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   at System.IO.Stream.BeginEndWriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at MaxTo.Core.Communication.NamedPipeServer.<Send>d__26.MoveNext()

-----------------
installer

2020-03-19 20:30:20> Program: Starting Squirrel Updater: --install .
2020-03-19 20:30:20> Program: Starting install, writing to C:\Users\UserName\AppData\Local\SquirrelTemp
2020-03-19 20:30:20> Program: About to install to: C:\Users\UserName\AppData\Local\MaxTo
2020-03-19 20:30:20> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\UserName\AppData\Local\MaxTo\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2020-03-19 20:30:20> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\UserName\AppData\Local\MaxTo\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2020-03-19 20:30:20> CheckForUpdateImpl: Reading RELEASES file from C:\Users\UserName\AppData\Local\SquirrelTemp
2020-03-19 20:30:20> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2020-03-19 20:30:20> ApplyReleasesImpl: Writing files to app directory: C:\Users\UserName\AppData\Local\MaxTo\app-2.0.1
2020-03-19 20:30:20> LogHost: Rigging execution stub for MaxTo.Companion.x64_ExecutionStub.exe to C:\Users\UserName\AppData\Local\MaxTo\MaxTo.Companion.x64.exe
2020-03-19 20:30:20> LogHost: Rigging execution stub for MaxTo.Companion.x86_ExecutionStub.exe to C:\Users\UserName\AppData\Local\MaxTo\MaxTo.Companion.x86.exe
2020-03-19 20:30:21> LogHost: Rigging execution stub for MaxTo.Core_ExecutionStub.exe to C:\Users\UserName\AppData\Local\MaxTo\MaxTo.Core.exe
2020-03-19 20:30:21> LogHost: Rigging execution stub for MaxTo.Server_ExecutionStub.exe to C:\Users\UserName\AppData\Local\MaxTo\MaxTo.Server.exe
2020-03-19 20:30:21> LogHost: Rigging execution stub for MaxTo.Server_ExecutionStub_ExecutionStub.exe to C:\Users\UserName\AppData\Local\MaxTo\MaxTo.Server_ExecutionStub.exe
2020-03-19 20:30:21> LogHost: Rigging execution stub for MaxTo.UI_ExecutionStub.exe to C:\Users\UserName\AppData\Local\MaxTo\MaxTo.UI.exe
2020-03-19 20:30:21> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\UserName\AppData\Local\MaxTo\app-2.0.1\MaxTo.Core.exe]
2020-03-19 20:30:23> ApplyReleasesImpl: Starting fixPinnedExecutables
2020-03-19 20:30:23> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2020-03-19 20:30:23> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2020-03-19 20:30:23> ApplyReleasesImpl: Fixing up tray icons
2020-03-19 20:30:23> ApplyReleasesImpl: cleanDeadVersions: for version 2.0.1
2020-03-19 20:30:23> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-2.0.1
```
-----------

**Comment by flyingwolf79** [comment]
Oh wow, an application like this has absolutely zero reasons to be reaching out to the internet, this is hinky, to say the least.

**Comment by vegardlarsen** [comment]
MaxTo contacts the web for 4 very legitimate reasons:

1. To check for updates. You [can disable this in settings](https://docs.maxto.net/reference/settings/updates). This is towards maxto.net, which is behind Cloudflare.
2. To update your compatibility shims. Cannot be disabled. Again towards maxto.net, again Cloudflare.
3. To check your license. You cannot disable this. This is also towards maxto.net, again Cloudflare.
4. MaxTo reports crashes to Raygun, which is likely the AWS entries you see. You can [disable this as well](https://docs.maxto.net/reference/settings/error-reporting).

It seems your firewall is blocking MaxTo's connection by denying access, which is simply something we haven't seen before, and therefore the exception is unhandled.

**Comment by byrongits** [comment]
Thank you very much, appreciate the response.  That is what I believed what was happening and I wanted to confirm.  However, I am confused to as why I disabled the automatic updates and the error reporting and it still attempts to connect.  

I recently saw new shims, although my automatic updates are disabled.  I've even disabled all of them - exepct for the ones you are not able to (Console windows & Specific Windows components).  Is this the expected behavior?  

It seems as if the updates are disabled, this should include shim updates.

For people with lifetime licenses, I understand you need to validate the license the first time.  However, if it is truely a lifetime license, why does it have to validate every time I launch the program?

**Comment by vegardlarsen** [comment]
So, there were a few questions in there.

Re: shims; you probably don't want to disable all of them. The option to disable shims is there only in case a program has fixed the issue the shim is made to counteract.

Second, updating shims should probably respect the auto-update settings, but it would also make more users exposed to misbehaving applications by not getting up-to-date shims. I think this is a trade-off.

Re: licenses; these licenses are digitally signed, and therefore MaxTo can validate that they were valid at the time of generation. However, because we have business licenses, which need updates, we sometimes "phone home" to check if the license is still valid. This functionality is also used to retract licenses in cases of refunds or other situations. However, if MaxTo does not have internet access, the license should remain valid, this check is only done if there is internet access.
