### ISSUE TITLE
I cannot install the app

### ISSUE THREAD

**Issue by ghost** [digitalcreations/MaxTo#794]
**Describe the bug**

Clicked on the installation file. Nothing happens, but I see something was installed. The shortcut does not exist and I can neither uninstall the app. If I try to install the app again, it throws back an error log at me. Now when I know this software does not work, how can I get rid of it completely?

```
---> (Inner Exception #0) System.UnauthorizedAccessException: Access to the path 'C:\Users\xccc\AppData\Local\MaxTo\app-2.2.1\MaxTo.Hook.x64.dll' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at Squirrel.Utility.<>c.<DeleteDirectory>b__19_0(String file)
   at Squirrel.Utility.<>c__DisplayClass12_1`1.<ForEachAsync>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass13_1`1.<<ForEachAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c.<<DeleteDirectory>b__19_1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass13_1`1.<<ForEachAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
```

**System information:**
- Windows version: 
- MaxTo version: 
Newest version, Windows 10

**Additional context**

**Comment by hralius** [comment]
I also get an error message when installing.

**Comment by martonkliniken** [comment]
hi i have same problem , and i wonder in the MAX to, it says you are expert on Windows, and wonder what kind of expert you are that it is common problem for other users as well

**Comment by hralius** [comment]
- I tried uninstalling Maxto, but it said that it was not correctly installed, and it could remove it from the list.
- Then I disabled some of the pre-installed Lenovo stuff that came with the PC... 
- Then I tried reinstalling, but it came up with a dialog stating that Maxto was already running.

So maybe Lenovo Vantage, or Lenovo Appearance, or whatever was the sinner, and cause of this issue.

**Comment by martonkliniken** [comment]
no i dont have lenovo it is dell and you are wrong

Den ons 2 aug. 2023 kl 22:50 skrev hralius ***@***.***>:

**Comment by hralius** [comment]
Dear @martonkliniken , 

I am not a the creator or supporter of this software, I am just a user like yourself.
I can only state what I did to resolve this issue.

Maybe you should contact the manufacturer directly - https://www.digitalcreations.no/
